In [1]:
from OSLPP import *
import torch
import torch.nn as nn
import torch.nn.functional as F
from collections import Counter
import os
import pandas as pd
from torch.optim.lr_scheduler import StepLR
import pickle

In [2]:
with open('small_datasets.pkl', 'rb') as f:
    config = pickle.load(f)

In [3]:
os.environ["CUDA_VISIBLE_DEVICES"] = '1'

In [4]:
def get_abbrev(source, target): return source[0].upper() + target[0].upper()
def fmeasures(d): return ' '.join([f'{k}={v*100:.2f}' for (k,v) in d.items()])

In [5]:
class FeaturesDataset(torch.utils.data.Dataset):
    def __init__(self, features, labels):
        self.features = features
        self.labels = labels
    def __len__(self): return len(self.labels)
    def __getitem__(self, i): return self.features[i], self.labels[i]

In [6]:
def _create_balanced_sampler(ds:FeaturesDataset):
    freq2 = Counter(ds.labels.tolist())
    class_weight = {x: 1.0 / freq2[x] for x in freq2}
    source_weights = [class_weight[x] for x in ds.labels.tolist()]
    sampler = torch.utils.data.WeightedRandomSampler(source_weights, len(ds.labels.tolist()))
    return sampler

def _create_trn_dataloader(ds, batch_size, balanced):
    if balanced: return torch.utils.data.DataLoader(ds, batch_size=batch_size, sampler=_create_balanced_sampler(ds), drop_last=True)
    else: torch.utils.data.DataLoader(ds, batch_size=batch_size, shuffle=True, drop_last=True)

In [7]:
def train_initial_NN(feats_S, lbls_S, num_epochs, params, balanced, lr):
    num_src_classes = params.num_common + params.num_src_priv
    assert (lbls_S.unique() == torch.arange(num_src_classes)).all()
    model = nn.Sequential(nn.Linear(params.pca_dim, params.proj_dim), nn.ReLU(), nn.Linear(params.proj_dim, num_src_classes)).cuda().train()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.CrossEntropyLoss().cuda()
    ds = FeaturesDataset(feats_S, lbls_S)
    dl = _create_trn_dataloader(ds, 32, balanced)
    for ep in range(num_epochs):
        for f,l in dl:
            optimizer.zero_grad()
            loss_fn(model(f.cuda()), l.cuda()).backward()
            optimizer.step()
    return model.eval()

In [8]:
def entropy_loss(logits):
    probs = F.softmax(logits, dim=1)
    entropy =  - probs * probs.log()
    entropy = entropy.sum(dim=1)
    return entropy.mean()

In [9]:
def train_NN(feats, lbls, num_epochs, params, balanced, lr):
    num_src_classes = params.num_common + params.num_src_priv
    feats, lbls = feats[lbls >= 0], lbls[lbls >= 0]
    feats, lbls = feats[lbls < num_src_classes + 1], lbls[lbls < num_src_classes + 1]
    model = nn.Sequential(nn.Linear(params.pca_dim, params.proj_dim), nn.ReLU(), nn.Linear(params.proj_dim, num_src_classes + 1)).cuda().train()
    optimizer = torch.optim.Adam(model.parameters(), lr=lr)
    loss_fn = nn.CrossEntropyLoss().cuda()
    ds = FeaturesDataset(feats, lbls)
    dl = _create_trn_dataloader(ds, 32, balanced)
    for ep in range(num_epochs):
        for f,l in dl:
            optimizer.zero_grad()
            loss_fn(model(f.cuda()), l.cuda()).backward()
            optimizer.step()
    return model.eval()

In [10]:
def predict_NN(model, feats, lbls):
    ds = FeaturesDataset(feats, lbls)
    dl = torch.utils.data.DataLoader(ds, batch_size=32, shuffle=False)
    model = model.eval()
    feats = []
    preds = []
    with torch.no_grad():
        for f,l in dl:
            out = model(f.cuda())
            preds.append(F.softmax(out, dim=1).detach().cpu())
            feats.append(f.detach())
    feats = torch.cat(feats, dim=0)
    preds = torch.cat(preds, dim=0)
    return feats, preds

In [11]:
def set_seed(seed:int):
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)

In [12]:
results = pd.DataFrame({'source': [], 'target': [], 'desc': [], 'lr': [], 'seed': [], 'epochs': []})
# select_reject_mode = SelectRejectMode.ENTROPY
select_reject_mode = SelectRejectMode.CONFIDENCE
# select_reject_mode = SelectRejectMode.MARGIN
for (source, target), (common, tgt_private) in config.items():
    for epochs in [10, 50]:
        for lr in [1e-3, 1e-4]:
            for n_r in [0.1, 0.25, 0.35]:
                for seed in range(3):
                    set_seed(seed)
                    print(source, '->', target, 'lr=', lr, 'seed=', seed)
                    params = Params(pca_dim=512, proj_dim=128, T=10, n_r=1200, n_r_ratio=None,
                              dataset='DomainNet_DCC', source=source, target=target,
                              num_common=len(common), num_src_priv=0, num_tgt_priv=len(tgt_private))
                    (feats_S, lbls_S), (feats_T, lbls_T) = create_datasets_sub(params.dataset, 
                                                                               params.source, 
                                                                               params.target, 
                                                                               common, 
                                                                               tgt_private)
                    params.n_r = int(len(lbls_T) * n_r)
                    num_src_classes = params.num_common + params.num_src_priv

                    # l2 normalization and pca
                    feats_S, feats_T = do_l2_normalization(feats_S, feats_T)
                    feats_S, feats_T = do_pca(feats_S, feats_T, params.pca_dim)
                    feats_S, feats_T = do_l2_normalization(feats_S, feats_T)

                    # initial
                    feats_S, feats_T = torch.tensor(feats_S), torch.tensor(feats_T)
                    lbls_S, lbls_T = torch.tensor(lbls_S), torch.tensor(lbls_T)
                    feats_all = torch.cat((feats_S, feats_T), dim=0)
                    pseudo_labels = -torch.ones_like(lbls_T)
                    rejected = torch.zeros_like(pseudo_labels)

                    t = 1

                    model = train_initial_NN(feats_S, lbls_S, epochs, params, balanced=True, lr=lr)
                    feats_S_2, preds_S_2 = predict_NN(model, feats_S, lbls_S)
                    feats_T_2, preds_T_2 = predict_NN(model, feats_T, lbls_T)
                    print((feats_S_2 == feats_S).all(), (feats_T_2 == feats_T).all())
                    assert (feats_S_2 == feats_S).all() and (feats_T_2 == feats_T).all()

                    if select_reject_mode == SelectRejectMode.CONFIDENCE:
                        confs, cs_pseudo_labels = preds_T_2.max(dim=1)
                        selected = select_closed_set_pseudo_labels(cs_pseudo_labels.numpy(), confs.numpy(), t, params.T, preds_T_2, select_reject_mode)
                        selected = torch.tensor(selected)
                        rejected = select_initial_rejected(confs, params.n_r)
                    elif select_reject_mode == SelectRejectMode.ENTROPY:
                        confs, cs_pseudo_labels = preds_T_2.max(dim=1)
                        selected = select_closed_set_pseudo_labels(cs_pseudo_labels.numpy(), confs.numpy(), t, params.T, preds_T_2, select_reject_mode)
                        selected = torch.tensor(selected)
                        rejected = select_initial_rejected_by_entropy(confs, params.n_r, preds_T_2)
                    elif select_reject_mode == SelectRejectMode.MARGIN:
                        confs, cs_pseudo_labels = preds_T_2.max(dim=1)
                        selected = select_closed_set_pseudo_labels(cs_pseudo_labels.numpy(), confs.numpy(), t, params.T, preds_T_2, select_reject_mode)
                        selected = torch.tensor(selected)
                        rejected = select_initial_rejected_by_margin(confs, params.n_r, preds_T_2)
                    else:
                        raise Exception('Incorrect mode.')
                        
                    rejected = torch.tensor(rejected)
                    selected = selected * (1 - rejected)
                    
                    pseudo_labels = cs_pseudo_labels.clone()
                    pseudo_labels[rejected == 1] = num_src_classes
                    pseudo_labels[(rejected == 0) * (selected == 0)] = -1

                    metrics = evaluate_T(params.num_common, params.num_src_priv, params.num_tgt_priv, 
                            lbls_T.numpy(), cs_pseudo_labels.numpy(), rejected.numpy())
                    where = torch.where((selected == 1) + (rejected == 1))[0]
                    metrics_selected = evaluate_T(params.num_common, params.num_src_priv, params.num_tgt_priv, lbls_T[where].numpy(), cs_pseudo_labels[where].numpy(), rejected[where].numpy())
                    print('______')
                    print(f'Iteration t={t}')
                    print('all: ', fmeasures(metrics))
                    print('selected: ', fmeasures(metrics_selected))

                    for t in range(2, params.T):
                        model = train_NN(feats_all, torch.cat((lbls_S, pseudo_labels), axis=0), epochs, params, balanced=True, lr=lr)
                        feats_S_2, preds_S_2 = predict_NN(model, feats_S, lbls_S)
                        feats_T_2, preds_T_2 = predict_NN(model, feats_T, lbls_T)
                        assert (feats_S_2 == feats_S).all() and (feats_T_2 == feats_T).all()

                        confs, cs_pseudo_labels = preds_T_2.max(dim=1)
                        selected = torch.tensor(select_closed_set_pseudo_labels(cs_pseudo_labels.numpy(), confs.numpy(), t, params.T, preds_T_2, select_reject_mode))
                        pseudo_labels = cs_pseudo_labels.clone()
                        pseudo_labels[selected == 0] = -1
                        print('Selected CNT:', len(selected[selected != 0]), '/', len(selected))

        
                        rejected = torch.zeros_like(pseudo_labels)
                        rejected[pseudo_labels == num_src_classes] = 1
            
                        metrics = evaluate_T(params.num_common, params.num_src_priv, params.num_tgt_priv, lbls_T.numpy(), cs_pseudo_labels.numpy(), rejected.numpy())
                        where = torch.where((selected == 1) + (rejected == 1))[0]
                        metrics_selected = evaluate_T(params.num_common, params.num_src_priv, params.num_tgt_priv, lbls_T[where].numpy(), cs_pseudo_labels[where].numpy(), rejected[where].numpy())
                        print('______')
                        print(f'Iteration t={t}')
                        print('all: ', fmeasures(metrics))
                        print('selected: ', fmeasures(metrics_selected))

                    print((pseudo_labels == -1).sum())

                    _rejected = rejected
                    metrics = evaluate_T(params.num_common, params.num_src_priv, params.num_tgt_priv, lbls_T.numpy(), cs_pseudo_labels.numpy(), _rejected.numpy())
                    print('all: ', fmeasures(metrics))

                    results = results.append({'source': source, 'target': target, 'desc': fmeasures(metrics), 'lr': lr, 'seed': seed, 'n_r': n_r, 'epochs': epochs}, ignore_index=True)

painting -> sketch lr= 0.001 seed= 0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=50.56 cs/acc_c=52.02 os/recall_knw=94.12 os/recall_unk=17.15 total/acc_i=37.72 total/acc_c=49.41 total/h_score=25.67
selected:  cs/acc_i=57.90 cs/acc_c=59.11 os/recall_knw=72.57 os/recall_unk=82.51 total/acc_i=63.57 total/acc_c=55.95 total/h_score=65.73
Selected CNT: 2155 / 9659
______
Iteration t=2
all:  cs/acc_i=39.01 cs/acc_c=40.37 os/recall_knw=95.45 os/recall_unk=20.53 total/acc_i=49.83 total/acc_c=41.72 total/h_score=50.85
selected:  cs/acc_i=57.99 cs/acc_c=59.83 os/recall_knw=78.88 os/recall_unk=86.69 total/acc_i=69.10 total/acc_c=61.10 total/h_score=70.80
Selected CNT: 3227 / 9659
______
Iteration t=3
all:  cs/acc_i=42.76 cs/acc_c=44.07 os/recall_knw=94.61 os/recall_unk=22.15 total/acc_i=47.33 total/acc_c=44.60 total/h_score=49.05
selected:  cs/acc_i=59.45

Selected CNT: 7522 / 9659
______
Iteration t=7
all:  cs/acc_i=47.91 cs/acc_c=49.27 os/recall_knw=89.73 os/recall_unk=34.78 total/acc_i=46.01 total/acc_c=48.96 total/h_score=45.75
selected:  cs/acc_i=53.27 cs/acc_c=54.43 os/recall_knw=87.24 os/recall_unk=47.43 total/acc_i=51.26 total/acc_c=54.10 total/h_score=50.69
Selected CNT: 8595 / 9659
______
Iteration t=8
all:  cs/acc_i=48.57 cs/acc_c=49.97 os/recall_knw=89.12 os/recall_unk=36.17 total/acc_i=45.44 total/acc_c=49.50 total/h_score=44.42
selected:  cs/acc_i=51.19 cs/acc_c=52.58 os/recall_knw=87.99 os/recall_unk=41.98 total/acc_i=47.93 total/acc_c=52.07 total/h_score=46.68
Selected CNT: 9659 / 9659
______
Iteration t=9
all:  cs/acc_i=48.85 cs/acc_c=50.27 os/recall_knw=87.45 os/recall_unk=40.23 total/acc_i=45.71 total/acc_c=49.80 total/h_score=44.70
selected:  cs/acc_i=48.85 cs/acc_c=50.27 os/recall_knw=87.45 os/recall_unk=40.23 total/acc_i=45.71 total/acc_c=49.80 total/h_score=44.70
tensor(0)
all:  cs/acc_i=48.85 cs/acc_c=50.27 os/rec

Selected CNT: 4304 / 9659
______
Iteration t=4
all:  cs/acc_i=43.98 cs/acc_c=45.39 os/recall_knw=92.41 os/recall_unk=26.60 total/acc_i=47.10 total/acc_c=45.73 total/h_score=48.70
selected:  cs/acc_i=57.34 cs/acc_c=58.41 os/recall_knw=84.06 os/recall_unk=67.85 total/acc_i=60.71 total/acc_c=58.86 total/h_score=62.78
Selected CNT: 5374 / 9659
______
Iteration t=5
all:  cs/acc_i=45.38 cs/acc_c=46.69 os/recall_knw=91.62 os/recall_unk=28.68 total/acc_i=45.94 total/acc_c=46.70 total/h_score=46.80
selected:  cs/acc_i=56.59 cs/acc_c=57.60 os/recall_knw=85.82 os/recall_unk=57.78 total/acc_i=56.98 total/acc_c=57.60 total/h_score=57.69
Selected CNT: 6444 / 9659
______
Iteration t=6
all:  cs/acc_i=47.22 cs/acc_c=48.57 os/recall_knw=90.76 os/recall_unk=31.20 total/acc_i=45.86 total/acc_c=48.33 total/h_score=45.89
selected:  cs/acc_i=55.39 cs/acc_c=56.49 os/recall_knw=86.85 os/recall_unk=51.52 total/acc_i=54.11 total/acc_c=56.26 total/h_score=53.89
Selected CNT: 7522 / 9659
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=50.35 cs/acc_c=51.97 os/recall_knw=73.73 os/recall_unk=50.20 total/acc_i=45.63 total/acc_c=44.77 total/h_score=47.17
selected:  cs/acc_i=43.85 cs/acc_c=45.81 os/recall_knw=37.01 os/recall_unk=92.95 total/acc_i=54.67 total/acc_c=30.96 total/h_score=42.87
Selected CNT: 2152 / 9659
______
Iteration t=2
all:  cs/acc_i=34.04 cs/acc_c=34.96 os/recall_knw=93.56 os/recall_unk=23.99 total/acc_i=50.19 total/acc_c=37.02 total/h_score=48.34
selected:  cs/acc_i=50.24 cs/acc_c=52.00 os/recall_knw=67.89 os/recall_unk=91.65 total/acc_i=67.98 total/acc_c=53.88 total/h_score=66.35
Selected CNT: 3226 / 9659
______
Iteration t=3
all:  cs/acc_i=40.07 cs/acc_c=41.21 os/recall_knw=92.49 os/recall_unk=26.21 total/acc_i=48.78 total/acc_c=42.29 total/h_score=50.13
selected:  cs/acc_i=57.48 cs/acc_c=58.89 os/recall_knw=78.03 o

Selected CNT: 7520 / 9659
______
Iteration t=7
all:  cs/acc_i=46.26 cs/acc_c=47.94 os/recall_knw=84.93 os/recall_unk=18.11 total/acc_i=38.62 total/acc_c=46.86 total/h_score=33.12
selected:  cs/acc_i=50.70 cs/acc_c=52.00 os/recall_knw=81.83 os/recall_unk=26.27 total/acc_i=42.81 total/acc_c=50.77 total/h_score=34.90
Selected CNT: 8597 / 9659
______
Iteration t=8
all:  cs/acc_i=46.75 cs/acc_c=48.52 os/recall_knw=82.09 os/recall_unk=21.41 total/acc_i=38.92 total/acc_c=47.41 total/h_score=33.23
selected:  cs/acc_i=49.10 cs/acc_c=50.49 os/recall_knw=80.53 os/recall_unk=25.53 total/acc_i=41.00 total/acc_c=49.30 total/h_score=33.92
Selected CNT: 9659 / 9659
______
Iteration t=9
all:  cs/acc_i=46.96 cs/acc_c=48.74 os/recall_knw=80.56 os/recall_unk=25.04 total/acc_i=38.97 total/acc_c=47.61 total/h_score=33.08
selected:  cs/acc_i=46.96 cs/acc_c=48.74 os/recall_knw=80.56 os/recall_unk=25.04 total/acc_i=38.97 total/acc_c=47.61 total/h_score=33.08
tensor(0)
all:  cs/acc_i=46.96 cs/acc_c=48.74 os/rec

Selected CNT: 4303 / 9659
______
Iteration t=4
all:  cs/acc_i=45.09 cs/acc_c=46.73 os/recall_knw=84.94 os/recall_unk=10.48 total/acc_i=40.38 total/acc_c=46.04 total/h_score=38.11
selected:  cs/acc_i=56.17 cs/acc_c=57.32 os/recall_knw=72.41 os/recall_unk=38.68 total/acc_i=52.29 total/acc_c=56.43 total/h_score=46.19
Selected CNT: 5376 / 9659
______
Iteration t=5
all:  cs/acc_i=45.84 cs/acc_c=47.51 os/recall_knw=81.55 os/recall_unk=12.15 total/acc_i=39.76 total/acc_c=46.64 total/h_score=36.14
selected:  cs/acc_i=54.09 cs/acc_c=55.33 os/recall_knw=71.66 os/recall_unk=30.99 total/acc_i=48.16 total/acc_c=54.17 total/h_score=39.73
Selected CNT: 6443 / 9659
______
Iteration t=6
all:  cs/acc_i=45.89 cs/acc_c=47.73 os/recall_knw=78.95 os/recall_unk=14.25 total/acc_i=38.92 total/acc_c=46.73 total/h_score=34.30
selected:  cs/acc_i=52.00 cs/acc_c=53.59 os/recall_knw=71.76 os/recall_unk=26.87 total/acc_i=44.72 total/acc_c=52.31 total/h_score=35.80
Selected CNT: 7522 / 9659
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=50.79 cs/acc_c=53.32 os/recall_knw=74.06 os/recall_unk=50.77 total/acc_i=47.68 total/acc_c=48.41 total/h_score=49.50
selected:  cs/acc_i=43.79 cs/acc_c=47.82 os/recall_knw=38.58 os/recall_unk=95.67 total/acc_i=58.80 total/acc_c=39.93 total/h_score=53.52
Selected CNT: 2155 / 9659
______
Iteration t=2
all:  cs/acc_i=44.63 cs/acc_c=46.32 os/recall_knw=92.50 os/recall_unk=9.45 total/acc_i=47.30 total/acc_c=46.59 total/h_score=48.98
selected:  cs/acc_i=56.76 cs/acc_c=58.31 os/recall_knw=72.83 os/recall_unk=72.08 total/acc_i=60.05 total/acc_c=58.97 total/h_score=64.47
Selected CNT: 3228 / 9659
______
Iteration t=3
all:  cs/acc_i=43.36 cs/acc_c=44.91 os/recall_knw=88.85 os/recall_unk=9.09 total/acc_i=40.90 total/acc_c=44.52 total/h_score=40.35
selected:  cs/acc_i=55.31 cs/acc_c=56.29 os/recall_knw=73.78 os/

Selected CNT: 7523 / 9659
______
Iteration t=7
all:  cs/acc_i=42.77 cs/acc_c=44.31 os/recall_knw=86.07 os/recall_unk=36.40 total/acc_i=43.49 total/acc_c=44.33 total/h_score=44.53
selected:  cs/acc_i=47.58 cs/acc_c=49.20 os/recall_knw=82.40 os/recall_unk=48.12 total/acc_i=47.77 total/acc_c=49.15 total/h_score=48.66
Selected CNT: 8596 / 9659
______
Iteration t=8
all:  cs/acc_i=43.43 cs/acc_c=45.02 os/recall_knw=84.41 os/recall_unk=39.27 total/acc_i=43.39 total/acc_c=44.94 total/h_score=44.16
selected:  cs/acc_i=45.74 cs/acc_c=47.49 os/recall_knw=82.63 os/recall_unk=44.82 total/acc_i=45.40 total/acc_c=47.36 total/h_score=46.11
Selected CNT: 9659 / 9659
______
Iteration t=9
all:  cs/acc_i=43.46 cs/acc_c=45.07 os/recall_knw=82.63 os/recall_unk=42.42 total/acc_i=43.08 total/acc_c=44.95 total/h_score=43.71
selected:  cs/acc_i=43.46 cs/acc_c=45.07 os/recall_knw=82.63 os/recall_unk=42.42 total/acc_i=43.08 total/acc_c=44.95 total/h_score=43.71
tensor(0)
all:  cs/acc_i=43.46 cs/acc_c=45.07 os/rec

Selected CNT: 4300 / 9659
______
Iteration t=4
all:  cs/acc_i=38.26 cs/acc_c=39.57 os/recall_knw=88.92 os/recall_unk=29.56 total/acc_i=44.99 total/acc_c=40.39 total/h_score=46.62
selected:  cs/acc_i=50.34 cs/acc_c=52.23 os/recall_knw=75.58 os/recall_unk=68.71 total/acc_i=56.81 total/acc_c=53.01 total/h_score=59.35
Selected CNT: 5374 / 9659
______
Iteration t=5
all:  cs/acc_i=39.87 cs/acc_c=41.24 os/recall_knw=86.83 os/recall_unk=33.13 total/acc_i=45.02 total/acc_c=41.85 total/h_score=46.76
selected:  cs/acc_i=49.20 cs/acc_c=50.86 os/recall_knw=76.98 os/recall_unk=62.61 total/acc_i=53.85 total/acc_c=51.42 total/h_score=56.13
Selected CNT: 6447 / 9659
______
Iteration t=6
all:  cs/acc_i=41.70 cs/acc_c=43.10 os/recall_knw=85.37 os/recall_unk=36.31 total/acc_i=44.99 total/acc_c=43.46 total/h_score=46.61
selected:  cs/acc_i=48.45 cs/acc_c=49.97 os/recall_knw=78.55 os/recall_unk=56.57 total/acc_i=51.30 total/acc_c=50.28 total/h_score=53.06
Selected CNT: 7522 / 9659
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=47.86 cs/acc_c=49.18 os/recall_knw=71.78 os/recall_unk=46.79 total/acc_i=42.53 total/acc_c=41.56 total/h_score=43.87
selected:  cs/acc_i=43.28 cs/acc_c=44.79 os/recall_knw=34.64 os/recall_unk=90.70 total/acc_i=51.89 total/acc_c=29.70 total/h_score=41.20
Selected CNT: 2159 / 9659
______
Iteration t=2
all:  cs/acc_i=28.06 cs/acc_c=28.95 os/recall_knw=90.42 os/recall_unk=23.94 total/acc_i=48.15 total/acc_c=31.53 total/h_score=42.95
selected:  cs/acc_i=38.86 cs/acc_c=41.69 os/recall_knw=52.88 os/recall_unk=92.54 total/acc_i=61.51 total/acc_c=44.11 total/h_score=57.48
Selected CNT: 3226 / 9659
______
Iteration t=3
all:  cs/acc_i=34.72 cs/acc_c=35.86 os/recall_knw=90.09 os/recall_unk=26.12 total/acc_i=45.66 total/acc_c=37.23 total/h_score=46.14
selected:  cs/acc_i=48.64 cs/acc_c=50.36 os/recall_knw=70.37 o

Selected CNT: 7519 / 9659
______
Iteration t=7
all:  cs/acc_i=40.46 cs/acc_c=41.97 os/recall_knw=81.49 os/recall_unk=41.48 total/acc_i=44.20 total/acc_c=42.39 total/h_score=45.93
selected:  cs/acc_i=45.02 cs/acc_c=46.66 os/recall_knw=76.63 os/recall_unk=54.95 total/acc_i=48.53 total/acc_c=47.05 total/h_score=50.46
Selected CNT: 8596 / 9659
______
Iteration t=8
all:  cs/acc_i=41.19 cs/acc_c=42.70 os/recall_knw=78.69 os/recall_unk=45.20 total/acc_i=44.39 total/acc_c=43.04 total/h_score=46.05
selected:  cs/acc_i=43.50 cs/acc_c=45.11 os/recall_knw=76.24 os/recall_unk=51.52 total/acc_i=46.38 total/acc_c=45.41 total/h_score=48.10
Selected CNT: 9659 / 9659
______
Iteration t=9
all:  cs/acc_i=41.27 cs/acc_c=42.79 os/recall_knw=75.85 os/recall_unk=49.20 total/acc_i=44.17 total/acc_c=43.10 total/h_score=45.77
selected:  cs/acc_i=41.27 cs/acc_c=42.79 os/recall_knw=75.85 os/recall_unk=49.20 total/acc_i=44.17 total/acc_c=43.10 total/h_score=45.77
tensor(0)
all:  cs/acc_i=41.27 cs/acc_c=42.79 os/rec

Selected CNT: 4301 / 9659
______
Iteration t=4
all:  cs/acc_i=45.72 cs/acc_c=47.18 os/recall_knw=94.05 os/recall_unk=21.75 total/acc_i=44.90 total/acc_c=47.01 total/h_score=45.25
selected:  cs/acc_i=59.79 cs/acc_c=61.40 os/recall_knw=87.93 os/recall_unk=59.98 total/acc_i=59.85 total/acc_c=61.33 total/h_score=60.68
Selected CNT: 5377 / 9659
______
Iteration t=5
all:  cs/acc_i=46.81 cs/acc_c=48.23 os/recall_knw=93.76 os/recall_unk=22.57 total/acc_i=43.24 total/acc_c=47.70 total/h_score=41.89
selected:  cs/acc_i=58.26 cs/acc_c=59.71 os/recall_knw=89.71 os/recall_unk=48.01 total/acc_i=55.11 total/acc_c=59.16 total/h_score=53.22
Selected CNT: 6447 / 9659
______
Iteration t=6
all:  cs/acc_i=47.91 cs/acc_c=49.30 os/recall_knw=93.37 os/recall_unk=23.76 total/acc_i=42.33 total/acc_c=48.51 total/h_score=39.26
selected:  cs/acc_i=56.50 cs/acc_c=57.46 os/recall_knw=90.66 os/recall_unk=40.03 total/acc_i=51.16 total/acc_c=56.63 total/h_score=47.19
Selected CNT: 7522 / 9659
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=51.34 cs/acc_c=52.78 os/recall_knw=84.01 os/recall_unk=40.69 total/acc_i=45.05 total/acc_c=48.60 total/h_score=44.46
selected:  cs/acc_i=48.20 cs/acc_c=49.54 os/recall_knw=49.49 os/recall_unk=92.21 total/acc_i=61.10 total/acc_c=40.53 total/h_score=53.77
Selected CNT: 2153 / 9659
______
Iteration t=2
all:  cs/acc_i=37.58 cs/acc_c=38.74 os/recall_knw=94.38 os/recall_unk=21.52 total/acc_i=50.91 total/acc_c=40.42 total/h_score=50.89
selected:  cs/acc_i=53.47 cs/acc_c=56.36 os/recall_knw=73.72 os/recall_unk=90.24 total/acc_i=67.81 total/acc_c=57.97 total/h_score=69.38
Selected CNT: 3226 / 9659
______
Iteration t=3
all:  cs/acc_i=42.55 cs/acc_c=43.92 os/recall_knw=93.38 os/recall_unk=21.66 total/acc_i=47.44 total/acc_c=44.49 total/h_score=49.21
selected:  cs/acc_i=57.84 cs/acc_c=59.41 os/recall_knw=81.81 o

Selected CNT: 7522 / 9659
______
Iteration t=7
all:  cs/acc_i=48.22 cs/acc_c=49.61 os/recall_knw=91.15 os/recall_unk=26.26 total/acc_i=42.23 total/acc_c=48.76 total/h_score=38.76
selected:  cs/acc_i=53.62 cs/acc_c=54.80 os/recall_knw=89.05 os/recall_unk=36.09 total/acc_i=47.65 total/acc_c=53.91 total/h_score=43.52
Selected CNT: 8596 / 9659
______
Iteration t=8
all:  cs/acc_i=48.72 cs/acc_c=50.10 os/recall_knw=90.37 os/recall_unk=27.43 total/acc_i=41.90 total/acc_c=49.14 total/h_score=37.54
selected:  cs/acc_i=51.31 cs/acc_c=52.58 os/recall_knw=89.39 os/recall_unk=31.92 total/acc_i=44.49 total/acc_c=51.60 total/h_score=39.73
Selected CNT: 9659 / 9659
______
Iteration t=9
all:  cs/acc_i=48.77 cs/acc_c=50.17 os/recall_knw=89.08 os/recall_unk=29.05 total/acc_i=41.58 total/acc_c=49.17 total/h_score=36.79
selected:  cs/acc_i=48.77 cs/acc_c=50.17 os/recall_knw=89.08 os/recall_unk=29.05 total/acc_i=41.58 total/acc_c=49.17 total/h_score=36.79
tensor(0)
all:  cs/acc_i=48.77 cs/acc_c=50.17 os/rec

Selected CNT: 3908 / 11705
______
Iteration t=3
all:  cs/acc_i=80.66 cs/acc_c=81.30 os/recall_knw=100.00 os/recall_unk=22.93 total/acc_i=76.67 total/acc_c=80.66 total/h_score=73.94
selected:  cs/acc_i=97.71 cs/acc_c=97.34 os/recall_knw=100.00 os/recall_unk=98.00 total/acc_i=97.77 total/acc_c=97.37 total/h_score=97.67
Selected CNT: 5210 / 11705
______
Iteration t=4
all:  cs/acc_i=81.21 cs/acc_c=81.82 os/recall_knw=100.00 os/recall_unk=27.25 total/acc_i=74.85 total/acc_c=80.81 total/h_score=69.71
selected:  cs/acc_i=95.84 cs/acc_c=95.24 os/recall_knw=100.00 os/recall_unk=94.11 total/acc_i=95.49 total/acc_c=95.19 total/h_score=94.67
Selected CNT: 6512 / 11705
______
Iteration t=5
all:  cs/acc_i=82.00 cs/acc_c=82.55 os/recall_knw=100.00 os/recall_unk=32.65 total/acc_i=74.67 total/acc_c=81.40 total/h_score=68.39
selected:  cs/acc_i=94.27 cs/acc_c=93.67 os/recall_knw=100.00 os/recall_unk=88.31 total/acc_i=93.04 total/acc_c=93.41 total/h_score=90.91
Selected CNT: 7812 / 11705
______
Iteration

Selected CNT: 11705 / 11705
______
Iteration t=9
all:  cs/acc_i=83.39 cs/acc_c=84.01 os/recall_knw=99.94 os/recall_unk=51.78 total/acc_i=73.58 total/acc_c=82.48 total/h_score=64.07
selected:  cs/acc_i=83.39 cs/acc_c=84.01 os/recall_knw=99.94 os/recall_unk=51.78 total/acc_i=73.58 total/acc_c=82.48 total/h_score=64.07
tensor(0)
all:  cs/acc_i=83.39 cs/acc_c=84.01 os/recall_knw=99.94 os/recall_unk=51.78 total/acc_i=73.58 total/acc_c=82.48 total/h_score=64.07
painting -> real lr= 0.001 seed= 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=79.91 cs/acc_c=80.57 os/recall_knw=90.31 os/recall_unk=59.01 total/acc_i=71.37 total/acc_c=76.83 total/h_score=67.09
selected:  cs/acc_i=73.45 cs/acc_c=75.27 os/recall_knw=62.53 os/recall_unk=99.81 total/acc_i=81.16 total/acc_c=66.49 total/h_score=78.60
Selected CNT: 2611 / 11705
______
Iteration t=2
all:  cs/acc_i

Selected CNT: 6514 / 11705
______
Iteration t=5
all:  cs/acc_i=81.79 cs/acc_c=82.52 os/recall_knw=100.00 os/recall_unk=33.66 total/acc_i=75.04 total/acc_c=81.46 total/h_score=69.52
selected:  cs/acc_i=94.28 cs/acc_c=93.66 os/recall_knw=100.00 os/recall_unk=89.08 total/acc_i=93.18 total/acc_c=93.44 total/h_score=91.31
Selected CNT: 7811 / 11705
______
Iteration t=6
all:  cs/acc_i=82.30 cs/acc_c=82.80 os/recall_knw=100.00 os/recall_unk=39.80 total/acc_i=75.16 total/acc_c=81.68 total/h_score=69.10
selected:  cs/acc_i=91.89 cs/acc_c=91.23 os/recall_knw=100.00 os/recall_unk=78.59 total/acc_i=88.76 total/acc_c=90.63 total/h_score=84.44
Selected CNT: 9114 / 11705
______
Iteration t=7
all:  cs/acc_i=82.27 cs/acc_c=82.75 os/recall_knw=100.00 os/recall_unk=45.20 total/acc_i=74.60 total/acc_c=81.55 total/h_score=67.89
selected:  cs/acc_i=89.38 cs/acc_c=88.95 os/recall_knw=100.00 os/recall_unk=69.43 total/acc_i=84.20 total/acc_c=88.02 total/h_score=77.99
Selected CNT: 10413 / 11705
______
Iteratio

tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=76.49 cs/acc_c=77.35 os/recall_knw=98.66 os/recall_unk=29.23 total/acc_i=61.59 total/acc_c=74.71 total/h_score=42.37
selected:  cs/acc_i=90.74 cs/acc_c=89.64 os/recall_knw=92.37 os/recall_unk=99.62 total/acc_i=93.47 total/acc_c=87.93 total/h_score=93.08
Selected CNT: 2611 / 11705
______
Iteration t=2
all:  cs/acc_i=77.64 cs/acc_c=78.55 os/recall_knw=100.00 os/recall_unk=17.62 total/acc_i=76.30 total/acc_c=78.30 total/h_score=75.85
selected:  cs/acc_i=96.08 cs/acc_c=95.18 os/recall_knw=100.00 os/recall_unk=98.77 total/acc_i=96.74 total/acc_c=95.35 total/h_score=96.94
Selected CNT: 3907 / 11705
______
Iteration t=3
all:  cs/acc_i=79.05 cs/acc_c=79.91 os/recall_knw=100.00 os/recall_unk=13.54 total/acc_i=66.81 total/acc_c=77.99 total/h_score=52.96
selected:  cs/acc_i=95.29 cs/acc_c=94.36 os/recall_knw=100.00 os/recall_unk=95.91 total/acc_i=95.37 total/acc_c=94.44 total/h_score=95.13
Selected CNT: 5212 / 11705
______
Iteration t=

Selected CNT: 9114 / 11705
______
Iteration t=7
all:  cs/acc_i=83.91 cs/acc_c=84.65 os/recall_knw=100.00 os/recall_unk=9.41 total/acc_i=61.61 total/acc_c=81.20 total/h_score=21.11
selected:  cs/acc_i=89.19 cs/acc_c=89.37 os/recall_knw=100.00 os/recall_unk=16.36 total/acc_i=72.49 total/acc_c=85.89 total/h_score=27.66
Selected CNT: 10414 / 11705
______
Iteration t=8
all:  cs/acc_i=84.19 cs/acc_c=84.89 os/recall_knw=100.00 os/recall_unk=10.57 total/acc_i=61.73 total/acc_c=81.41 total/h_score=20.78
selected:  cs/acc_i=87.63 cs/acc_c=88.07 os/recall_knw=100.00 os/recall_unk=13.18 total/acc_i=66.79 total/acc_c=84.51 total/h_score=22.93
Selected CNT: 11705 / 11705
______
Iteration t=9
all:  cs/acc_i=84.56 cs/acc_c=85.27 os/recall_knw=99.99 os/recall_unk=12.00 total/acc_i=62.04 total/acc_c=81.78 total/h_score=21.04
selected:  cs/acc_i=84.56 cs/acc_c=85.27 os/recall_knw=99.99 os/recall_unk=12.00 total/acc_i=62.04 total/acc_c=81.78 total/h_score=21.04
tensor(0)
all:  cs/acc_i=84.56 cs/acc_c=85.2

Selected CNT: 3910 / 11705
______
Iteration t=3
all:  cs/acc_i=78.95 cs/acc_c=79.88 os/recall_knw=100.00 os/recall_unk=16.02 total/acc_i=68.94 total/acc_c=78.30 total/h_score=58.93
selected:  cs/acc_i=95.13 cs/acc_c=94.27 os/recall_knw=100.00 os/recall_unk=96.20 total/acc_i=95.29 total/acc_c=94.36 total/h_score=95.22
Selected CNT: 5209 / 11705
______
Iteration t=4
all:  cs/acc_i=81.37 cs/acc_c=82.25 os/recall_knw=100.00 os/recall_unk=13.02 total/acc_i=65.09 total/acc_c=79.71 total/h_score=42.80
selected:  cs/acc_i=94.00 cs/acc_c=93.12 os/recall_knw=100.00 os/recall_unk=86.95 total/acc_i=93.26 total/acc_c=92.82 total/h_score=89.93
Selected CNT: 6513 / 11705
______
Iteration t=5
all:  cs/acc_i=82.21 cs/acc_c=83.05 os/recall_knw=100.00 os/recall_unk=14.56 total/acc_i=64.77 total/acc_c=80.33 total/h_score=39.62
selected:  cs/acc_i=91.88 cs/acc_c=91.21 os/recall_knw=100.00 os/recall_unk=63.35 total/acc_i=88.22 total/acc_c=89.89 total/h_score=74.77
Selected CNT: 7810 / 11705
______
Iteration

Selected CNT: 11705 / 11705
______
Iteration t=9
all:  cs/acc_i=84.27 cs/acc_c=85.01 os/recall_knw=99.96 os/recall_unk=25.71 total/acc_i=66.09 total/acc_c=82.18 total/h_score=39.48
selected:  cs/acc_i=84.27 cs/acc_c=85.01 os/recall_knw=99.96 os/recall_unk=25.71 total/acc_i=66.09 total/acc_c=82.18 total/h_score=39.48
tensor(0)
all:  cs/acc_i=84.27 cs/acc_c=85.01 os/recall_knw=99.96 os/recall_unk=25.71 total/acc_i=66.09 total/acc_c=82.18 total/h_score=39.48
painting -> real lr= 0.0001 seed= 2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=76.66 cs/acc_c=77.45 os/recall_knw=86.68 os/recall_unk=83.15 total/acc_i=74.87 total/acc_c=72.57 total/h_score=77.20
selected:  cs/acc_i=71.78 cs/acc_c=75.51 os/recall_knw=54.85 os/recall_unk=99.87 total/acc_i=79.25 total/acc_c=61.14 total/h_score=74.34
Selected CNT: 2612 / 11705
______
Iteration t=2
all:  cs/acc_

Selected CNT: 6513 / 11705
______
Iteration t=5
all:  cs/acc_i=78.65 cs/acc_c=79.40 os/recall_knw=99.99 os/recall_unk=35.43 total/acc_i=73.75 total/acc_c=78.62 total/h_score=70.16
selected:  cs/acc_i=92.31 cs/acc_c=91.33 os/recall_knw=99.98 os/recall_unk=86.90 total/acc_i=91.08 total/acc_c=91.12 total/h_score=89.06
Selected CNT: 7809 / 11705
______
Iteration t=6
all:  cs/acc_i=78.91 cs/acc_c=79.68 os/recall_knw=99.96 os/recall_unk=41.43 total/acc_i=73.48 total/acc_c=78.81 total/h_score=69.36
selected:  cs/acc_i=89.41 cs/acc_c=88.71 os/recall_knw=99.95 os/recall_unk=79.67 total/acc_i=87.05 total/acc_c=88.28 total/h_score=83.95
Selected CNT: 9113 / 11705
______
Iteration t=7
all:  cs/acc_i=78.90 cs/acc_c=79.72 os/recall_knw=99.96 os/recall_unk=47.18 total/acc_i=73.10 total/acc_c=78.79 total/h_score=68.60
selected:  cs/acc_i=85.85 cs/acc_c=85.68 os/recall_knw=99.96 os/recall_unk=71.21 total/acc_i=81.98 total/acc_c=84.99 total/h_score=77.78
Selected CNT: 10417 / 11705
______
Iteration t=8


tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=77.18 cs/acc_c=78.06 os/recall_knw=86.00 os/recall_unk=49.44 total/acc_i=65.19 total/acc_c=71.90 total/h_score=58.96
selected:  cs/acc_i=70.92 cs/acc_c=72.43 os/recall_knw=56.87 os/recall_unk=99.34 total/acc_i=73.60 total/acc_c=58.63 total/h_score=72.11
Selected CNT: 2629 / 11705
______
Iteration t=2
all:  cs/acc_i=62.49 cs/acc_c=63.41 os/recall_knw=98.85 os/recall_unk=33.11 total/acc_i=71.79 total/acc_c=64.79 total/h_score=75.23
selected:  cs/acc_i=92.12 cs/acc_c=89.60 os/recall_knw=93.46 os/recall_unk=99.59 total/acc_i=95.55 total/acc_c=90.08 total/h_score=94.33
Selected CNT: 3922 / 11705
______
Iteration t=3
all:  cs/acc_i=74.41 cs/acc_c=75.47 os/recall_knw=99.83 os/recall_unk=30.14 total/acc_i=75.04 total/acc_c=75.51 total/h_score=75.96
selected:  cs/acc_i=95.66 cs/acc_c=94.49 os/recall_knw=99.50 os/recall_unk=98.83 total/acc_i=96.56 total/acc_c=94.70 total/h_score=96.61
Selected CNT: 5221 / 11705
______
Iteration t=4
al

Selected CNT: 9115 / 11705
______
Iteration t=7
all:  cs/acc_i=78.78 cs/acc_c=79.49 os/recall_knw=99.91 os/recall_unk=49.05 total/acc_i=73.77 total/acc_c=78.69 total/h_score=70.07
selected:  cs/acc_i=85.54 cs/acc_c=85.22 os/recall_knw=99.90 os/recall_unk=73.39 total/acc_i=82.30 total/acc_c=84.65 total/h_score=78.86
Selected CNT: 10416 / 11705
______
Iteration t=8
all:  cs/acc_i=78.85 cs/acc_c=79.58 os/recall_knw=99.89 os/recall_unk=53.92 total/acc_i=73.11 total/acc_c=78.66 total/h_score=68.65
selected:  cs/acc_i=82.45 cs/acc_c=82.69 os/recall_knw=99.88 os/recall_unk=66.00 total/acc_i=77.76 total/acc_c=81.90 total/h_score=73.41
Selected CNT: 11705 / 11705
______
Iteration t=9
all:  cs/acc_i=79.00 cs/acc_c=79.75 os/recall_knw=99.78 os/recall_unk=59.92 total/acc_i=73.08 total/acc_c=78.81 total/h_score=68.43
selected:  cs/acc_i=79.00 cs/acc_c=79.75 os/recall_knw=99.78 os/recall_unk=59.92 total/acc_i=73.08 total/acc_c=78.81 total/h_score=68.43
tensor(0)
all:  cs/acc_i=79.00 cs/acc_c=79.75 o

Selected CNT: 3907 / 11705
______
Iteration t=3
all:  cs/acc_i=81.47 cs/acc_c=82.22 os/recall_knw=100.00 os/recall_unk=20.64 total/acc_i=75.20 total/acc_c=81.22 total/h_score=70.22
selected:  cs/acc_i=97.38 cs/acc_c=96.90 os/recall_knw=100.00 os/recall_unk=96.77 total/acc_i=97.26 total/acc_c=96.90 total/h_score=96.84
Selected CNT: 5210 / 11705
______
Iteration t=4
all:  cs/acc_i=82.27 cs/acc_c=82.94 os/recall_knw=100.00 os/recall_unk=21.28 total/acc_i=71.47 total/acc_c=81.25 total/h_score=60.39
selected:  cs/acc_i=95.41 cs/acc_c=94.93 os/recall_knw=100.00 os/recall_unk=86.47 total/acc_i=93.88 total/acc_c=94.53 total/h_score=90.50
Selected CNT: 6515 / 11705
______
Iteration t=5
all:  cs/acc_i=82.94 cs/acc_c=83.69 os/recall_knw=100.00 os/recall_unk=23.59 total/acc_i=70.28 total/acc_c=81.71 total/h_score=56.06
selected:  cs/acc_i=93.75 cs/acc_c=93.39 os/recall_knw=100.00 os/recall_unk=67.80 total/acc_i=88.72 total/acc_c=92.17 total/h_score=78.56
Selected CNT: 7810 / 11705
______
Iteration

Selected CNT: 11705 / 11705
______
Iteration t=9
all:  cs/acc_i=84.45 cs/acc_c=85.30 os/recall_knw=99.95 os/recall_unk=38.62 total/acc_i=70.23 total/acc_c=83.08 total/h_score=53.17
selected:  cs/acc_i=84.45 cs/acc_c=85.30 os/recall_knw=99.95 os/recall_unk=38.62 total/acc_i=70.23 total/acc_c=83.08 total/h_score=53.17
tensor(0)
all:  cs/acc_i=84.45 cs/acc_c=85.30 os/recall_knw=99.95 os/recall_unk=38.62 total/acc_i=70.23 total/acc_c=83.08 total/h_score=53.17
painting -> real lr= 0.0001 seed= 0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=80.46 cs/acc_c=81.31 os/recall_knw=92.07 os/recall_unk=62.92 total/acc_i=73.26 total/acc_c=78.00 total/h_score=69.95
selected:  cs/acc_i=76.89 cs/acc_c=78.91 os/recall_knw=67.06 os/recall_unk=99.78 total/acc_i=84.41 total/acc_c=69.71 total/h_score=81.02
Selected CNT: 2610 / 11705
______
Iteration t=2
all:  cs/acc_

Selected CNT: 6511 / 11705
______
Iteration t=5
all:  cs/acc_i=82.99 cs/acc_c=83.67 os/recall_knw=100.00 os/recall_unk=29.78 total/acc_i=73.76 total/acc_c=82.22 total/h_score=65.09
selected:  cs/acc_i=94.45 cs/acc_c=94.08 os/recall_knw=100.00 os/recall_unk=84.07 total/acc_i=92.40 total/acc_c=93.61 total/h_score=88.80
Selected CNT: 7811 / 11705
______
Iteration t=6
all:  cs/acc_i=83.33 cs/acc_c=84.00 os/recall_knw=100.00 os/recall_unk=32.29 total/acc_i=72.40 total/acc_c=82.29 total/h_score=61.21
selected:  cs/acc_i=92.55 cs/acc_c=92.32 os/recall_knw=100.00 os/recall_unk=68.92 total/acc_i=87.40 total/acc_c=91.20 total/h_score=78.92
Selected CNT: 9113 / 11705
______
Iteration t=7
all:  cs/acc_i=83.67 cs/acc_c=84.40 os/recall_knw=100.00 os/recall_unk=34.60 total/acc_i=71.46 total/acc_c=82.49 total/h_score=58.12
selected:  cs/acc_i=90.23 cs/acc_c=90.22 os/recall_knw=100.00 os/recall_unk=55.45 total/acc_i=81.58 total/acc_c=88.56 total/h_score=68.68
Selected CNT: 10411 / 11705
______
Iteratio

tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=80.09 cs/acc_c=80.94 os/recall_knw=84.89 os/recall_unk=79.16 total/acc_i=76.01 total/acc_c=75.80 total/h_score=77.36
selected:  cs/acc_i=68.69 cs/acc_c=72.66 os/recall_knw=51.70 os/recall_unk=99.83 total/acc_i=77.07 total/acc_c=58.94 total/h_score=72.48
Selected CNT: 2611 / 11705
______
Iteration t=2
all:  cs/acc_i=73.82 cs/acc_c=74.97 os/recall_knw=99.98 os/recall_unk=27.09 total/acc_i=79.07 total/acc_c=75.72 total/h_score=82.10
selected:  cs/acc_i=98.52 cs/acc_c=97.82 os/recall_knw=99.88 os/recall_unk=99.80 total/acc_i=99.00 total/acc_c=97.92 total/h_score=98.80
Selected CNT: 3909 / 11705
______
Iteration t=3
all:  cs/acc_i=80.76 cs/acc_c=81.51 os/recall_knw=100.00 os/recall_unk=23.20 total/acc_i=76.86 total/acc_c=80.88 total/h_score=74.25
selected:  cs/acc_i=97.51 cs/acc_c=97.04 os/recall_knw=100.00 os/recall_unk=98.02 total/acc_i=97.62 total/acc_c=97.08 total/h_score=97.53
Selected CNT: 5214 / 11705
______
Iteration t=4


Selected CNT: 7498 / 9632
______
Iteration t=7
all:  cs/acc_i=67.44 cs/acc_c=66.78 os/recall_knw=90.72 os/recall_unk=40.88 total/acc_i=61.99 total/acc_c=66.00 total/h_score=57.51
selected:  cs/acc_i=72.59 cs/acc_c=71.85 os/recall_knw=88.55 os/recall_unk=57.41 total/acc_i=68.12 total/acc_c=71.16 total/h_score=63.82
Selected CNT: 8570 / 9632
______
Iteration t=8
all:  cs/acc_i=68.45 cs/acc_c=67.81 os/recall_knw=89.91 os/recall_unk=43.82 total/acc_i=61.94 total/acc_c=66.88 total/h_score=56.35
selected:  cs/acc_i=71.00 cs/acc_c=70.31 os/recall_knw=88.91 os/recall_unk=51.67 total/acc_i=65.08 total/acc_c=69.42 total/h_score=59.57
Selected CNT: 9632 / 9632
______
Iteration t=9
all:  cs/acc_i=68.48 cs/acc_c=67.83 os/recall_knw=88.15 os/recall_unk=47.82 total/acc_i=61.84 total/acc_c=66.88 total/h_score=56.10
selected:  cs/acc_i=68.48 cs/acc_c=67.83 os/recall_knw=88.15 os/recall_unk=47.82 total/acc_i=61.84 total/acc_c=66.88 total/h_score=56.10
tensor(0)
all:  cs/acc_i=68.48 cs/acc_c=67.83 os/rec

Selected CNT: 4292 / 9632
______
Iteration t=4
all:  cs/acc_i=64.96 cs/acc_c=64.45 os/recall_knw=93.16 os/recall_unk=31.40 total/acc_i=64.61 total/acc_c=64.42 total/h_score=64.15
selected:  cs/acc_i=77.58 cs/acc_c=76.75 os/recall_knw=85.64 os/recall_unk=82.53 total/acc_i=78.94 total/acc_c=77.03 total/h_score=79.54
Selected CNT: 5361 / 9632
______
Iteration t=5
all:  cs/acc_i=66.28 cs/acc_c=65.87 os/recall_knw=91.99 os/recall_unk=36.53 total/acc_i=64.80 total/acc_c=65.67 total/h_score=63.72
selected:  cs/acc_i=75.95 cs/acc_c=75.29 os/recall_knw=86.55 os/recall_unk=76.85 total/acc_i=76.20 total/acc_c=75.36 total/h_score=76.06
Selected CNT: 6429 / 9632
______
Iteration t=6
all:  cs/acc_i=66.81 cs/acc_c=66.29 os/recall_knw=90.94 os/recall_unk=41.17 total/acc_i=64.20 total/acc_c=65.93 total/h_score=62.26
selected:  cs/acc_i=74.43 cs/acc_c=73.70 os/recall_knw=87.11 os/recall_unk=69.46 total/acc_i=73.01 total/acc_c=73.50 total/h_score=71.52
Selected CNT: 7503 / 9632
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=73.70 cs/acc_c=73.45 os/recall_knw=76.92 os/recall_unk=60.12 total/acc_i=63.68 total/acc_c=64.95 total/h_score=62.55
selected:  cs/acc_i=59.97 cs/acc_c=60.65 os/recall_knw=40.82 os/recall_unk=97.85 total/acc_i=63.95 total/acc_c=42.90 total/h_score=56.94
Selected CNT: 2152 / 9632
______
Iteration t=2
all:  cs/acc_i=52.70 cs/acc_c=51.89 os/recall_knw=94.31 os/recall_unk=26.69 total/acc_i=64.45 total/acc_c=53.67 total/h_score=65.62
selected:  cs/acc_i=69.12 cs/acc_c=68.37 os/recall_knw=71.43 os/recall_unk=97.29 total/acc_i=80.25 total/acc_c=69.75 total/h_score=80.31
Selected CNT: 3218 / 9632
______
Iteration t=3
all:  cs/acc_i=61.38 cs/acc_c=60.68 os/recall_knw=93.80 os/recall_unk=30.11 total/acc_i=65.86 total/acc_c=61.37 total/h_score=67.21
selected:  cs/acc_i=76.43 cs/acc_c=75.57 os/recall_knw=81.67 o

Selected CNT: 7501 / 9632
______
Iteration t=7
all:  cs/acc_i=69.19 cs/acc_c=68.92 os/recall_knw=86.61 os/recall_unk=20.65 total/acc_i=56.06 total/acc_c=66.99 total/h_score=40.22
selected:  cs/acc_i=73.07 cs/acc_c=72.81 os/recall_knw=83.98 os/recall_unk=31.40 total/acc_i=61.75 total/acc_c=70.84 total/h_score=43.88
Selected CNT: 8571 / 9632
______
Iteration t=8
all:  cs/acc_i=69.34 cs/acc_c=69.05 os/recall_knw=85.21 os/recall_unk=23.62 total/acc_i=55.99 total/acc_c=67.09 total/h_score=39.69
selected:  cs/acc_i=71.32 cs/acc_c=70.95 os/recall_knw=84.09 os/recall_unk=29.30 total/acc_i=59.07 total/acc_c=68.97 total/h_score=41.48
Selected CNT: 9632 / 9632
______
Iteration t=9
all:  cs/acc_i=69.65 cs/acc_c=69.40 os/recall_knw=84.69 os/recall_unk=25.91 total/acc_i=55.58 total/acc_c=67.33 total/h_score=37.73
selected:  cs/acc_i=69.65 cs/acc_c=69.40 os/recall_knw=84.69 os/recall_unk=25.91 total/acc_i=55.58 total/acc_c=67.33 total/h_score=37.73
tensor(0)
all:  cs/acc_i=69.65 cs/acc_c=69.40 os/rec

Selected CNT: 4289 / 9632
______
Iteration t=4
all:  cs/acc_i=66.05 cs/acc_c=65.69 os/recall_knw=90.11 os/recall_unk=16.75 total/acc_i=57.90 total/acc_c=64.50 total/h_score=50.28
selected:  cs/acc_i=74.28 cs/acc_c=74.24 os/recall_knw=81.03 os/recall_unk=58.78 total/acc_i=71.09 total/acc_c=73.51 total/h_score=65.61
Selected CNT: 5361 / 9632
______
Iteration t=5
all:  cs/acc_i=67.58 cs/acc_c=67.23 os/recall_knw=88.84 os/recall_unk=18.01 total/acc_i=57.28 total/acc_c=65.72 total/h_score=46.52
selected:  cs/acc_i=74.14 cs/acc_c=73.92 os/recall_knw=82.37 os/recall_unk=45.48 total/acc_i=67.58 total/acc_c=72.56 total/h_score=56.31
Selected CNT: 6427 / 9632
______
Iteration t=6
all:  cs/acc_i=67.89 cs/acc_c=67.57 os/recall_knw=87.13 os/recall_unk=20.30 total/acc_i=56.62 total/acc_c=65.92 total/h_score=44.24
selected:  cs/acc_i=73.43 cs/acc_c=73.17 os/recall_knw=82.45 os/recall_unk=38.45 total/acc_i=64.52 total/acc_c=71.51 total/h_score=50.41
Selected CNT: 7500 / 9632
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=74.04 cs/acc_c=73.80 os/recall_knw=78.59 os/recall_unk=63.63 total/acc_i=65.77 total/acc_c=66.53 total/h_score=65.12
selected:  cs/acc_i=59.87 cs/acc_c=61.04 os/recall_knw=42.36 os/recall_unk=97.53 total/acc_i=66.33 total/acc_c=45.69 total/h_score=59.78
Selected CNT: 2150 / 9632
______
Iteration t=2
all:  cs/acc_i=61.61 cs/acc_c=61.13 os/recall_knw=93.85 os/recall_unk=17.39 total/acc_i=66.26 total/acc_c=61.84 total/h_score=67.78
selected:  cs/acc_i=70.41 cs/acc_c=71.54 os/recall_knw=74.20 os/recall_unk=91.05 total/acc_i=76.09 total/acc_c=72.47 total/h_score=80.12
Selected CNT: 3220 / 9632
______
Iteration t=3
all:  cs/acc_i=63.81 cs/acc_c=63.24 os/recall_knw=91.81 os/recall_unk=16.84 total/acc_i=60.13 total/acc_c=62.72 total/h_score=57.30
selected:  cs/acc_i=73.57 cs/acc_c=73.57 os/recall_knw=78.90 o

Selected CNT: 7499 / 9632
______
Iteration t=7
all:  cs/acc_i=68.38 cs/acc_c=68.16 os/recall_knw=86.29 os/recall_unk=20.91 total/acc_i=55.68 total/acc_c=66.29 total/h_score=40.60
selected:  cs/acc_i=72.18 cs/acc_c=72.06 os/recall_knw=83.59 os/recall_unk=31.80 total/acc_i=61.21 total/acc_c=70.14 total/h_score=44.12
Selected CNT: 8570 / 9632
______
Iteration t=8
all:  cs/acc_i=69.26 cs/acc_c=69.07 os/recall_knw=85.70 os/recall_unk=22.30 total/acc_i=55.42 total/acc_c=67.03 total/h_score=38.03
selected:  cs/acc_i=71.32 cs/acc_c=71.10 os/recall_knw=84.58 os/recall_unk=27.49 total/acc_i=58.46 total/acc_c=69.02 total/h_score=39.65
Selected CNT: 9632 / 9632
______
Iteration t=9
all:  cs/acc_i=69.74 cs/acc_c=69.53 os/recall_knw=84.82 os/recall_unk=24.56 total/acc_i=55.20 total/acc_c=67.39 total/h_score=36.29
selected:  cs/acc_i=69.74 cs/acc_c=69.53 os/recall_knw=84.82 os/recall_unk=24.56 total/acc_i=55.20 total/acc_c=67.39 total/h_score=36.29
tensor(0)
all:  cs/acc_i=69.74 cs/acc_c=69.53 os/rec

Selected CNT: 4293 / 9632
______
Iteration t=4
all:  cs/acc_i=61.72 cs/acc_c=61.13 os/recall_knw=91.89 os/recall_unk=31.88 total/acc_i=62.35 total/acc_c=61.25 total/h_score=62.39
selected:  cs/acc_i=74.49 cs/acc_c=73.84 os/recall_knw=82.82 os/recall_unk=81.79 total/acc_i=76.54 total/acc_c=74.22 total/h_score=77.61
Selected CNT: 5360 / 9632
______
Iteration t=5
all:  cs/acc_i=62.71 cs/acc_c=62.19 os/recall_knw=90.65 os/recall_unk=35.27 total/acc_i=61.30 total/acc_c=62.01 total/h_score=60.19
selected:  cs/acc_i=73.35 cs/acc_c=72.69 os/recall_knw=84.08 os/recall_unk=71.81 total/acc_i=72.91 total/acc_c=72.65 total/h_score=72.25
Selected CNT: 6429 / 9632
______
Iteration t=6
all:  cs/acc_i=63.77 cs/acc_c=63.28 os/recall_knw=89.61 os/recall_unk=38.43 total/acc_i=60.81 total/acc_c=62.86 total/h_score=58.60
selected:  cs/acc_i=71.24 cs/acc_c=70.70 os/recall_knw=85.14 os/recall_unk=64.03 total/acc_i=69.16 total/acc_c=70.38 total/h_score=67.20
Selected CNT: 7502 / 9632
______
Iteration t=7
all: 

Selected CNT: 7501 / 9632
______
Iteration t=7
all:  cs/acc_i=63.23 cs/acc_c=62.67 os/recall_knw=85.58 os/recall_unk=44.60 total/acc_i=60.64 total/acc_c=62.32 total/h_score=58.69
selected:  cs/acc_i=68.25 cs/acc_c=67.62 os/recall_knw=81.99 os/recall_unk=60.83 total/acc_i=66.00 total/acc_c=67.30 total/h_score=64.04
Selected CNT: 8572 / 9632
______
Iteration t=8
all:  cs/acc_i=63.42 cs/acc_c=62.83 os/recall_knw=83.44 os/recall_unk=48.24 total/acc_i=60.17 total/acc_c=62.38 total/h_score=57.70
selected:  cs/acc_i=66.14 cs/acc_c=65.46 os/recall_knw=81.67 os/recall_unk=56.03 total/acc_i=63.00 total/acc_c=65.02 total/h_score=60.38
Selected CNT: 9632 / 9632
______
Iteration t=9
all:  cs/acc_i=63.75 cs/acc_c=63.24 os/recall_knw=81.49 os/recall_unk=52.21 total/acc_i=60.04 total/acc_c=62.72 total/h_score=57.20
selected:  cs/acc_i=63.75 cs/acc_c=63.24 os/recall_knw=81.49 os/recall_unk=52.21 total/acc_i=60.04 total/acc_c=62.72 total/h_score=57.20
tensor(0)
all:  cs/acc_i=63.75 cs/acc_c=63.24 os/rec

Selected CNT: 4309 / 9632
______
Iteration t=4
all:  cs/acc_i=61.12 cs/acc_c=60.31 os/recall_knw=91.05 os/recall_unk=33.56 total/acc_i=63.06 total/acc_c=60.64 total/h_score=63.55
selected:  cs/acc_i=73.69 cs/acc_c=72.55 os/recall_knw=81.00 os/recall_unk=84.55 total/acc_i=76.79 total/acc_c=73.13 total/h_score=78.10
Selected CNT: 5359 / 9632
______
Iteration t=5
all:  cs/acc_i=62.31 cs/acc_c=61.61 os/recall_knw=89.91 os/recall_unk=37.72 total/acc_i=62.33 total/acc_c=61.64 total/h_score=61.99
selected:  cs/acc_i=72.72 cs/acc_c=71.74 os/recall_knw=82.75 os/recall_unk=75.96 total/acc_i=73.65 total/acc_c=71.94 total/h_score=73.79
Selected CNT: 6428 / 9632
______
Iteration t=6
all:  cs/acc_i=63.69 cs/acc_c=63.03 os/recall_knw=88.73 os/recall_unk=42.27 total/acc_i=62.40 total/acc_c=62.87 total/h_score=61.30
selected:  cs/acc_i=71.19 cs/acc_c=70.35 os/recall_knw=83.71 os/recall_unk=68.62 total/acc_i=70.43 total/acc_c=70.27 total/h_score=69.47
Selected CNT: 7501 / 9632
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=74.94 cs/acc_c=74.82 os/recall_knw=95.21 os/recall_unk=20.97 total/acc_i=56.81 total/acc_c=71.22 total/h_score=32.66
selected:  cs/acc_i=79.20 cs/acc_c=77.07 os/recall_knw=76.75 os/recall_unk=93.12 total/acc_i=80.33 total/acc_c=72.95 total/h_score=81.18
Selected CNT: 2152 / 9632
______
Iteration t=2
all:  cs/acc_i=61.12 cs/acc_c=60.42 os/recall_knw=95.47 os/recall_unk=21.43 total/acc_i=67.20 total/acc_c=61.36 total/h_score=68.86
selected:  cs/acc_i=76.93 cs/acc_c=75.89 os/recall_knw=79.56 os/recall_unk=94.32 total/acc_i=82.62 total/acc_c=76.77 total/h_score=84.11
Selected CNT: 3218 / 9632
______
Iteration t=3
all:  cs/acc_i=66.08 cs/acc_c=65.43 os/recall_knw=94.64 os/recall_unk=21.94 total/acc_i=64.15 total/acc_c=65.18 total/h_score=62.64
selected:  cs/acc_i=79.55 cs/acc_c=78.54 os/recall_knw=85.48 o

Selected CNT: 7500 / 9632
______
Iteration t=7
all:  cs/acc_i=69.51 cs/acc_c=68.88 os/recall_knw=90.74 os/recall_unk=38.24 total/acc_i=62.58 total/acc_c=67.88 total/h_score=56.56
selected:  cs/acc_i=74.36 cs/acc_c=73.58 os/recall_knw=88.60 os/recall_unk=54.06 total/acc_i=68.43 total/acc_c=72.65 total/h_score=62.33
Selected CNT: 8569 / 9632
______
Iteration t=8
all:  cs/acc_i=69.86 cs/acc_c=69.23 os/recall_knw=89.71 os/recall_unk=41.24 total/acc_i=62.15 total/acc_c=68.12 total/h_score=55.19
selected:  cs/acc_i=72.45 cs/acc_c=71.76 os/recall_knw=88.72 os/recall_unk=48.98 total/acc_i=65.31 total/acc_c=70.68 total/h_score=58.22
Selected CNT: 9632 / 9632
______
Iteration t=9
all:  cs/acc_i=70.30 cs/acc_c=69.68 os/recall_knw=88.58 os/recall_unk=45.14 total/acc_i=62.21 total/acc_c=68.51 total/h_score=54.79
selected:  cs/acc_i=70.30 cs/acc_c=69.68 os/recall_knw=88.58 os/recall_unk=45.14 total/acc_i=62.21 total/acc_c=68.51 total/h_score=54.79
tensor(0)
all:  cs/acc_i=70.30 cs/acc_c=69.68 os/rec

Selected CNT: 4289 / 9632
______
Iteration t=4
all:  cs/acc_i=66.68 cs/acc_c=66.08 os/recall_knw=92.87 os/recall_unk=27.17 total/acc_i=63.73 total/acc_c=65.68 total/h_score=61.50
selected:  cs/acc_i=78.04 cs/acc_c=77.07 os/recall_knw=85.51 os/recall_unk=78.40 total/acc_i=78.13 total/acc_c=77.14 total/h_score=77.73
Selected CNT: 5360 / 9632
______
Iteration t=5
all:  cs/acc_i=67.72 cs/acc_c=67.06 os/recall_knw=91.99 os/recall_unk=31.43 total/acc_i=63.24 total/acc_c=66.43 total/h_score=59.70
selected:  cs/acc_i=77.19 cs/acc_c=76.32 os/recall_knw=86.79 os/recall_unk=69.47 total/acc_i=75.17 total/acc_c=76.00 total/h_score=72.74
Selected CNT: 6427 / 9632
______
Iteration t=6
all:  cs/acc_i=68.35 cs/acc_c=67.72 os/recall_knw=90.95 os/recall_unk=35.66 total/acc_i=62.90 total/acc_c=66.94 total/h_score=58.46
selected:  cs/acc_i=75.54 cs/acc_c=74.76 os/recall_knw=87.25 os/recall_unk=61.73 total/acc_i=71.70 total/acc_c=74.14 total/h_score=67.62
Selected CNT: 7500 / 9632
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=57.43 cs/acc_c=56.51 os/recall_knw=92.69 os/recall_unk=14.94 total/acc_i=42.00 total/acc_c=53.84 total/h_score=23.57
selected:  cs/acc_i=69.51 cs/acc_c=64.19 os/recall_knw=69.38 os/recall_unk=91.61 total/acc_i=73.17 total/acc_c=62.53 total/h_score=73.29
Selected CNT: 2181 / 9767
______
Iteration t=2
all:  cs/acc_i=43.96 cs/acc_c=43.28 os/recall_knw=91.54 os/recall_unk=20.09 total/acc_i=55.85 total/acc_c=44.92 total/h_score=55.61
selected:  cs/acc_i=60.74 cs/acc_c=57.13 os/recall_knw=63.09 os/recall_unk=94.65 total/acc_i=72.08 total/acc_c=58.92 total/h_score=71.25
Selected CNT: 3260 / 9767
______
Iteration t=3
all:  cs/acc_i=48.11 cs/acc_c=47.28 os/recall_knw=89.88 os/recall_unk=22.68 total/acc_i=53.02 total/acc_c=47.98 total/h_score=53.67
selected:  cs/acc_i=67.99 cs/acc_c=63.10 os/recall_knw=72.86 o

Selected CNT: 7605 / 9767
______
Iteration t=7
all:  cs/acc_i=52.34 cs/acc_c=51.58 os/recall_knw=84.46 os/recall_unk=36.23 total/acc_i=49.86 total/acc_c=51.28 total/h_score=48.22
selected:  cs/acc_i=58.82 cs/acc_c=56.68 os/recall_knw=80.91 os/recall_unk=50.78 total/acc_i=56.23 total/acc_c=56.40 total/h_score=53.57
Selected CNT: 8691 / 9767
______
Iteration t=8
all:  cs/acc_i=52.52 cs/acc_c=51.71 os/recall_knw=82.93 os/recall_unk=39.75 total/acc_i=49.45 total/acc_c=51.34 total/h_score=47.43
selected:  cs/acc_i=56.01 cs/acc_c=54.49 os/recall_knw=81.17 os/recall_unk=46.29 total/acc_i=52.71 total/acc_c=54.10 total/h_score=50.06
Selected CNT: 9767 / 9767
______
Iteration t=9
all:  cs/acc_i=52.87 cs/acc_c=52.11 os/recall_knw=81.05 os/recall_unk=43.16 total/acc_i=49.45 total/acc_c=51.68 total/h_score=47.21
selected:  cs/acc_i=52.87 cs/acc_c=52.11 os/recall_knw=81.05 os/recall_unk=43.16 total/acc_i=49.45 total/acc_c=51.68 total/h_score=47.21
tensor(0)
all:  cs/acc_i=52.87 cs/acc_c=52.11 os/rec

Selected CNT: 4352 / 9767
______
Iteration t=4
all:  cs/acc_i=49.25 cs/acc_c=48.55 os/recall_knw=88.11 os/recall_unk=26.30 total/acc_i=51.38 total/acc_c=48.88 total/h_score=51.71
selected:  cs/acc_i=66.75 cs/acc_c=62.49 os/recall_knw=76.16 os/recall_unk=75.63 total/acc_i=69.19 total/acc_c=63.11 total/h_score=68.43
Selected CNT: 5434 / 9767
______
Iteration t=5
all:  cs/acc_i=50.67 cs/acc_c=49.96 os/recall_knw=86.72 os/recall_unk=30.78 total/acc_i=51.13 total/acc_c=50.05 total/h_score=50.95
selected:  cs/acc_i=64.45 cs/acc_c=60.93 os/recall_knw=78.00 os/recall_unk=65.61 total/acc_i=64.80 total/acc_c=61.15 total/h_score=63.18
Selected CNT: 6516 / 9767
______
Iteration t=6
all:  cs/acc_i=52.11 cs/acc_c=51.37 os/recall_knw=86.33 os/recall_unk=32.50 total/acc_i=50.02 total/acc_c=51.12 total/h_score=48.62
selected:  cs/acc_i=62.22 cs/acc_c=59.51 os/recall_knw=80.70 os/recall_unk=54.98 total/acc_i=59.96 total/acc_c=59.29 total/h_score=57.15
Selected CNT: 7604 / 9767
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=55.39 cs/acc_c=54.82 os/recall_knw=93.38 os/recall_unk=16.22 total/acc_i=41.23 total/acc_c=52.41 total/h_score=24.97
selected:  cs/acc_i=70.12 cs/acc_c=63.93 os/recall_knw=71.28 os/recall_unk=91.16 total/acc_i=74.49 total/acc_c=62.90 total/h_score=73.44
Selected CNT: 2181 / 9767
______
Iteration t=2
all:  cs/acc_i=43.42 cs/acc_c=42.65 os/recall_knw=90.05 os/recall_unk=17.01 total/acc_i=54.93 total/acc_c=44.24 total/h_score=54.68
selected:  cs/acc_i=57.41 cs/acc_c=55.10 os/recall_knw=59.59 os/recall_unk=93.89 total/acc_i=67.81 total/acc_c=56.95 total/h_score=69.45
Selected CNT: 3262 / 9767
______
Iteration t=3
all:  cs/acc_i=46.20 cs/acc_c=45.72 os/recall_knw=87.34 os/recall_unk=19.39 total/acc_i=50.66 total/acc_c=46.35 total/h_score=51.47
selected:  cs/acc_i=63.29 cs/acc_c=60.46 os/recall_knw=67.06 o

Selected CNT: 7605 / 9767
______
Iteration t=7
all:  cs/acc_i=50.21 cs/acc_c=50.10 os/recall_knw=78.75 os/recall_unk=32.15 total/acc_i=47.23 total/acc_c=49.70 total/h_score=45.53
selected:  cs/acc_i=56.64 cs/acc_c=55.14 os/recall_knw=73.73 os/recall_unk=44.50 total/acc_i=52.68 total/acc_c=54.63 total/h_score=49.25
Selected CNT: 8692 / 9767
______
Iteration t=8
all:  cs/acc_i=50.66 cs/acc_c=50.46 os/recall_knw=77.29 os/recall_unk=34.01 total/acc_i=46.24 total/acc_c=49.87 total/h_score=43.41
selected:  cs/acc_i=53.84 cs/acc_c=53.01 os/recall_knw=74.83 os/recall_unk=39.21 total/acc_i=48.83 total/acc_c=52.35 total/h_score=45.08
Selected CNT: 9767 / 9767
______
Iteration t=9
all:  cs/acc_i=50.54 cs/acc_c=50.28 os/recall_knw=75.21 os/recall_unk=36.66 total/acc_i=45.66 total/acc_c=49.63 total/h_score=42.40
selected:  cs/acc_i=50.54 cs/acc_c=50.28 os/recall_knw=75.21 os/recall_unk=36.66 total/acc_i=45.66 total/acc_c=49.63 total/h_score=42.40
tensor(0)
all:  cs/acc_i=50.54 cs/acc_c=50.28 os/rec

Selected CNT: 4349 / 9767
______
Iteration t=4
all:  cs/acc_i=49.14 cs/acc_c=48.81 os/recall_knw=84.70 os/recall_unk=21.93 total/acc_i=49.79 total/acc_c=48.91 total/h_score=49.87
selected:  cs/acc_i=64.01 cs/acc_c=61.63 os/recall_knw=70.37 os/recall_unk=69.79 total/acc_i=65.44 total/acc_c=62.02 total/h_score=65.45
Selected CNT: 5435 / 9767
______
Iteration t=5
all:  cs/acc_i=50.34 cs/acc_c=50.09 os/recall_knw=82.69 os/recall_unk=24.99 total/acc_i=48.86 total/acc_c=49.90 total/h_score=48.03
selected:  cs/acc_i=62.65 cs/acc_c=60.36 os/recall_knw=72.36 os/recall_unk=58.37 total/acc_i=61.49 total/acc_c=60.27 total/h_score=59.35
Selected CNT: 6517 / 9767
______
Iteration t=6
all:  cs/acc_i=50.42 cs/acc_c=50.26 os/recall_knw=80.39 os/recall_unk=27.87 total/acc_i=47.69 total/acc_c=49.90 total/h_score=46.15
selected:  cs/acc_i=59.89 cs/acc_c=57.97 os/recall_knw=72.59 os/recall_unk=48.21 total/acc_i=56.33 total/acc_c=57.50 total/h_score=52.64
Selected CNT: 7607 / 9767
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=54.90 cs/acc_c=54.27 os/recall_knw=73.17 os/recall_unk=50.06 total/acc_i=50.47 total/acc_c=50.08 total/h_score=50.07
selected:  cs/acc_i=45.90 cs/acc_c=45.68 os/recall_knw=38.06 os/recall_unk=97.12 total/acc_i=60.07 total/acc_c=38.67 total/h_score=52.26
Selected CNT: 2183 / 9767
______
Iteration t=2
all:  cs/acc_i=42.55 cs/acc_c=41.92 os/recall_knw=89.01 os/recall_unk=17.38 total/acc_i=56.05 total/acc_c=43.78 total/h_score=55.23
selected:  cs/acc_i=53.76 cs/acc_c=53.54 os/recall_knw=55.30 os/recall_unk=95.37 total/acc_i=65.69 total/acc_c=55.54 total/h_score=68.58
Selected CNT: 3264 / 9767
______
Iteration t=3
all:  cs/acc_i=47.73 cs/acc_c=47.15 os/recall_knw=87.56 os/recall_unk=18.03 total/acc_i=50.80 total/acc_c=47.59 total/h_score=51.39
selected:  cs/acc_i=63.74 cs/acc_c=61.68 os/recall_knw=68.21 o

Selected CNT: 7605 / 9767
______
Iteration t=7
all:  cs/acc_i=48.63 cs/acc_c=47.84 os/recall_knw=80.04 os/recall_unk=38.32 total/acc_i=48.47 total/acc_c=47.85 total/h_score=48.00
selected:  cs/acc_i=54.18 cs/acc_c=52.39 os/recall_knw=75.00 os/recall_unk=51.65 total/acc_i=53.33 total/acc_c=52.36 total/h_score=52.02
Selected CNT: 8690 / 9767
______
Iteration t=8
all:  cs/acc_i=48.74 cs/acc_c=47.96 os/recall_knw=78.05 os/recall_unk=42.28 total/acc_i=48.09 total/acc_c=47.91 total/h_score=47.41
selected:  cs/acc_i=51.77 cs/acc_c=50.59 os/recall_knw=75.70 os/recall_unk=48.89 total/acc_i=50.78 total/acc_c=50.51 total/h_score=49.72
Selected CNT: 9767 / 9767
______
Iteration t=9
all:  cs/acc_i=48.71 cs/acc_c=47.95 os/recall_knw=74.69 os/recall_unk=48.17 total/acc_i=48.52 total/acc_c=47.96 total/h_score=48.06
selected:  cs/acc_i=48.71 cs/acc_c=47.95 os/recall_knw=74.69 os/recall_unk=48.17 total/acc_i=48.52 total/acc_c=47.96 total/h_score=48.06
tensor(0)
all:  cs/acc_i=48.71 cs/acc_c=47.95 os/rec

Selected CNT: 4350 / 9767
______
Iteration t=4
all:  cs/acc_i=44.77 cs/acc_c=43.96 os/recall_knw=85.19 os/recall_unk=29.56 total/acc_i=50.53 total/acc_c=44.78 total/h_score=51.15
selected:  cs/acc_i=59.98 cs/acc_c=56.38 os/recall_knw=68.95 os/recall_unk=76.37 total/acc_i=64.99 total/acc_c=57.33 total/h_score=64.87
Selected CNT: 5438 / 9767
______
Iteration t=5
all:  cs/acc_i=46.41 cs/acc_c=45.64 os/recall_knw=83.07 os/recall_unk=33.11 total/acc_i=49.75 total/acc_c=46.13 total/h_score=50.26
selected:  cs/acc_i=58.32 cs/acc_c=55.42 os/recall_knw=71.34 os/recall_unk=66.96 total/acc_i=61.02 total/acc_c=55.97 total/h_score=60.65
Selected CNT: 6521 / 9767
______
Iteration t=6
all:  cs/acc_i=46.83 cs/acc_c=46.11 os/recall_knw=81.24 os/recall_unk=36.28 total/acc_i=48.70 total/acc_c=46.40 total/h_score=48.95
selected:  cs/acc_i=55.89 cs/acc_c=53.64 os/recall_knw=73.07 os/recall_unk=59.08 total/acc_i=56.92 total/acc_c=53.90 total/h_score=56.23
Selected CNT: 7604 / 9767
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=54.71 cs/acc_c=53.87 os/recall_knw=71.53 os/recall_unk=47.03 total/acc_i=47.97 total/acc_c=47.76 total/h_score=47.41
selected:  cs/acc_i=47.93 cs/acc_c=47.31 os/recall_knw=36.65 os/recall_unk=95.39 total/acc_i=56.93 total/acc_c=36.49 total/h_score=49.63
Selected CNT: 2241 / 9767
______
Iteration t=2
all:  cs/acc_i=35.02 cs/acc_c=34.44 os/recall_knw=88.47 os/recall_unk=22.71 total/acc_i=53.54 total/acc_c=36.97 total/h_score=49.45
selected:  cs/acc_i=46.38 cs/acc_c=44.73 os/recall_knw=48.70 os/recall_unk=95.35 total/acc_i=64.26 total/acc_c=47.14 total/h_score=60.90
Selected CNT: 3276 / 9767
______
Iteration t=3
all:  cs/acc_i=41.83 cs/acc_c=41.11 os/recall_knw=86.75 os/recall_unk=25.31 total/acc_i=51.34 total/acc_c=42.43 total/h_score=51.49
selected:  cs/acc_i=57.40 cs/acc_c=54.19 os/recall_knw=62.96 o

Selected CNT: 7608 / 9767
______
Iteration t=7
all:  cs/acc_i=53.96 cs/acc_c=53.23 os/recall_knw=85.63 os/recall_unk=32.73 total/acc_i=49.63 total/acc_c=52.67 total/h_score=46.73
selected:  cs/acc_i=60.75 cs/acc_c=58.80 os/recall_knw=82.35 os/recall_unk=45.86 total/acc_i=55.95 total/acc_c=58.19 total/h_score=51.53
Selected CNT: 8691 / 9767
______
Iteration t=8
all:  cs/acc_i=54.11 cs/acc_c=53.40 os/recall_knw=84.21 os/recall_unk=35.70 total/acc_i=49.12 total/acc_c=52.76 total/h_score=45.69
selected:  cs/acc_i=57.66 cs/acc_c=56.31 os/recall_knw=82.60 os/recall_unk=41.63 total/acc_i=52.23 total/acc_c=55.61 total/h_score=47.87
Selected CNT: 9767 / 9767
______
Iteration t=9
all:  cs/acc_i=54.19 cs/acc_c=53.48 os/recall_knw=82.60 os/recall_unk=39.08 total/acc_i=48.88 total/acc_c=52.80 total/h_score=45.16
selected:  cs/acc_i=54.19 cs/acc_c=53.48 os/recall_knw=82.60 os/recall_unk=39.08 total/acc_i=48.88 total/acc_c=52.80 total/h_score=45.16
tensor(0)
all:  cs/acc_i=54.19 cs/acc_c=53.48 os/rec

Selected CNT: 4353 / 9767
______
Iteration t=4
all:  cs/acc_i=51.35 cs/acc_c=50.69 os/recall_knw=88.35 os/recall_unk=23.56 total/acc_i=51.57 total/acc_c=50.75 total/h_score=51.33
selected:  cs/acc_i=69.06 cs/acc_c=65.14 os/recall_knw=77.12 os/recall_unk=71.78 total/acc_i=69.77 total/acc_c=65.45 total/h_score=68.30
Selected CNT: 5434 / 9767
______
Iteration t=5
all:  cs/acc_i=52.60 cs/acc_c=51.83 os/recall_knw=87.34 os/recall_unk=27.26 total/acc_i=50.93 total/acc_c=51.64 total/h_score=49.76
selected:  cs/acc_i=67.08 cs/acc_c=63.72 os/recall_knw=79.49 os/recall_unk=61.42 total/acc_i=65.50 total/acc_c=63.61 total/h_score=62.55
Selected CNT: 6520 / 9767
______
Iteration t=6
all:  cs/acc_i=53.66 cs/acc_c=52.83 os/recall_knw=86.18 os/recall_unk=30.66 total/acc_i=50.69 total/acc_c=52.47 total/h_score=48.73
selected:  cs/acc_i=63.81 cs/acc_c=61.11 os/recall_knw=80.79 os/recall_unk=53.56 total/acc_i=60.72 total/acc_c=60.75 total/h_score=57.09
Selected CNT: 7606 / 9767
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=57.41 cs/acc_c=56.69 os/recall_knw=74.10 os/recall_unk=51.78 total/acc_i=52.69 total/acc_c=52.54 total/h_score=52.17
selected:  cs/acc_i=47.77 cs/acc_c=47.54 os/recall_knw=39.03 os/recall_unk=97.59 total/acc_i=61.95 total/acc_c=40.48 total/h_score=54.31
Selected CNT: 2182 / 9767
______
Iteration t=2
all:  cs/acc_i=41.92 cs/acc_c=41.28 os/recall_knw=90.07 os/recall_unk=21.08 total/acc_i=56.95 total/acc_c=43.35 total/h_score=55.50
selected:  cs/acc_i=54.58 cs/acc_c=53.46 os/recall_knw=56.04 os/recall_unk=96.40 total/acc_i=68.97 total/acc_c=55.50 total/h_score=68.78
Selected CNT: 3264 / 9767
______
Iteration t=3
all:  cs/acc_i=48.48 cs/acc_c=47.76 os/recall_knw=89.63 os/recall_unk=21.20 total/acc_i=52.54 total/acc_c=48.35 total/h_score=53.21
selected:  cs/acc_i=68.87 cs/acc_c=64.51 os/recall_knw=72.73 o

Selected CNT: 7604 / 9767
______
Iteration t=7
all:  cs/acc_i=53.70 cs/acc_c=52.96 os/recall_knw=85.09 os/recall_unk=32.29 total/acc_i=49.23 total/acc_c=52.39 total/h_score=46.20
selected:  cs/acc_i=60.59 cs/acc_c=58.47 os/recall_knw=81.69 os/recall_unk=45.30 total/acc_i=55.67 total/acc_c=57.85 total/h_score=51.05
Selected CNT: 8692 / 9767
______
Iteration t=8
all:  cs/acc_i=53.84 cs/acc_c=53.14 os/recall_knw=83.77 os/recall_unk=34.83 total/acc_i=48.66 total/acc_c=52.48 total/h_score=45.06
selected:  cs/acc_i=57.36 cs/acc_c=56.00 os/recall_knw=82.19 os/recall_unk=40.94 total/acc_i=51.84 total/acc_c=55.28 total/h_score=47.30
Selected CNT: 9767 / 9767
______
Iteration t=9
all:  cs/acc_i=54.14 cs/acc_c=53.43 os/recall_knw=82.11 os/recall_unk=38.21 total/acc_i=48.54 total/acc_c=52.71 total/h_score=44.55
selected:  cs/acc_i=54.14 cs/acc_c=53.43 os/recall_knw=82.11 os/recall_unk=38.21 total/acc_i=48.54 total/acc_c=52.71 total/h_score=44.55
tensor(0)
all:  cs/acc_i=54.14 cs/acc_c=53.43 os/rec

Selected CNT: 3932 / 11775
______
Iteration t=3
all:  cs/acc_i=84.88 cs/acc_c=86.12 os/recall_knw=99.92 os/recall_unk=21.45 total/acc_i=75.90 total/acc_c=84.77 total/h_score=69.19
selected:  cs/acc_i=98.31 cs/acc_c=97.95 os/recall_knw=99.80 os/recall_unk=97.22 total/acc_i=98.07 total/acc_c=97.91 total/h_score=97.58
Selected CNT: 5243 / 11775
______
Iteration t=4
all:  cs/acc_i=87.94 cs/acc_c=88.90 os/recall_knw=99.91 os/recall_unk=24.39 total/acc_i=76.47 total/acc_c=87.20 total/h_score=66.69
selected:  cs/acc_i=97.39 cs/acc_c=97.01 os/recall_knw=99.83 os/recall_unk=93.16 total/acc_i=96.57 total/acc_c=96.83 total/h_score=95.05
Selected CNT: 6551 / 11775
______
Iteration t=5
all:  cs/acc_i=88.99 cs/acc_c=89.85 os/recall_knw=99.89 os/recall_unk=28.38 total/acc_i=76.10 total/acc_c=87.96 total/h_score=64.36
selected:  cs/acc_i=96.85 cs/acc_c=96.54 os/recall_knw=99.83 os/recall_unk=82.03 total/acc_i=93.79 total/acc_c=95.85 total/h_score=88.69
Selected CNT: 7858 / 11775
______
Iteration t=6
a

Selected CNT: 11775 / 11775
______
Iteration t=9
all:  cs/acc_i=89.93 cs/acc_c=90.69 os/recall_knw=99.56 os/recall_unk=42.90 total/acc_i=74.33 total/acc_c=88.42 total/h_score=58.25
selected:  cs/acc_i=89.93 cs/acc_c=90.69 os/recall_knw=99.56 os/recall_unk=42.90 total/acc_i=74.33 total/acc_c=88.42 total/h_score=58.25
tensor(0)
all:  cs/acc_i=89.93 cs/acc_c=90.69 os/recall_knw=99.56 os/recall_unk=42.90 total/acc_i=74.33 total/acc_c=88.42 total/h_score=58.25
sketch -> real lr= 0.001 seed= 2
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=84.43 cs/acc_c=85.61 os/recall_knw=89.95 os/recall_unk=55.08 total/acc_i=72.55 total/acc_c=81.37 total/h_score=66.12
selected:  cs/acc_i=73.69 cs/acc_c=79.22 os/recall_knw=62.30 os/recall_unk=99.54 total/acc_i=80.89 total/acc_c=70.89 total/h_score=81.82
Selected CNT: 2626 / 11775
______
Iteration t=2
all:  cs/acc_i=7

Selected CNT: 6551 / 11775
______
Iteration t=5
all:  cs/acc_i=88.31 cs/acc_c=89.21 os/recall_knw=99.89 os/recall_unk=31.66 total/acc_i=77.47 total/acc_c=87.61 total/h_score=68.54
selected:  cs/acc_i=96.72 cs/acc_c=96.50 os/recall_knw=99.82 os/recall_unk=82.85 total/acc_i=93.56 total/acc_c=95.85 total/h_score=89.16
Selected CNT: 7858 / 11775
______
Iteration t=6
all:  cs/acc_i=88.99 cs/acc_c=89.82 os/recall_knw=99.85 os/recall_unk=37.86 total/acc_i=77.99 total/acc_c=88.20 total/h_score=68.85
selected:  cs/acc_i=95.86 cs/acc_c=95.67 os/recall_knw=99.80 os/recall_unk=76.00 total/acc_i=90.94 total/acc_c=94.73 total/h_score=84.71
Selected CNT: 9168 / 11775
______
Iteration t=7
all:  cs/acc_i=89.30 cs/acc_c=90.11 os/recall_knw=99.75 os/recall_unk=44.46 total/acc_i=78.39 total/acc_c=88.51 total/h_score=69.41
selected:  cs/acc_i=94.58 cs/acc_c=94.60 os/recall_knw=99.70 os/recall_unk=67.88 total/acc_i=87.13 total/acc_c=93.32 total/h_score=79.04
Selected CNT: 10478 / 11775
______
Iteration t=8


tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=71.91 cs/acc_c=71.19 os/recall_knw=97.23 os/recall_unk=24.55 total/acc_i=55.66 total/acc_c=68.15 total/h_score=36.39
selected:  cs/acc_i=86.02 cs/acc_c=83.71 os/recall_knw=85.55 os/recall_unk=97.06 total/acc_i=87.87 total/acc_c=79.12 total/h_score=86.63
Selected CNT: 2626 / 11775
______
Iteration t=2
all:  cs/acc_i=71.72 cs/acc_c=71.45 os/recall_knw=99.96 os/recall_unk=20.66 total/acc_i=71.07 total/acc_c=71.37 total/h_score=70.59
selected:  cs/acc_i=96.85 cs/acc_c=95.58 os/recall_knw=99.83 os/recall_unk=98.90 total/acc_i=97.49 total/acc_c=95.74 total/h_score=97.21
Selected CNT: 3932 / 11775
______
Iteration t=3
all:  cs/acc_i=78.66 cs/acc_c=78.56 os/recall_knw=99.96 os/recall_unk=19.53 total/acc_i=69.99 total/acc_c=77.32 total/h_score=62.96
selected:  cs/acc_i=96.18 cs/acc_c=94.94 os/recall_knw=99.90 os/recall_unk=90.19 total/acc_i=94.89 total/acc_c=94.71 total/h_score=92.50
Selected CNT: 5243 / 11775
______
Iteration t=4
al

Selected CNT: 9168 / 11775
______
Iteration t=7
all:  cs/acc_i=86.62 cs/acc_c=87.12 os/recall_knw=99.86 os/recall_unk=31.23 total/acc_i=70.99 total/acc_c=84.86 total/h_score=54.37
selected:  cs/acc_i=90.95 cs/acc_c=90.90 os/recall_knw=99.83 os/recall_unk=46.62 total/acc_i=78.29 total/acc_c=88.79 total/h_score=61.63
Selected CNT: 10475 / 11775
______
Iteration t=8
all:  cs/acc_i=86.86 cs/acc_c=87.33 os/recall_knw=99.78 os/recall_unk=35.37 total/acc_i=71.04 total/acc_c=85.04 total/h_score=54.10
selected:  cs/acc_i=89.43 cs/acc_c=89.60 os/recall_knw=99.77 os/recall_unk=43.19 total/acc_i=75.30 total/acc_c=87.39 total/h_score=58.28
Selected CNT: 11775 / 11775
______
Iteration t=9
all:  cs/acc_i=86.90 cs/acc_c=87.38 os/recall_knw=99.47 os/recall_unk=37.65 total/acc_i=70.56 total/acc_c=85.01 total/h_score=52.62
selected:  cs/acc_i=86.90 cs/acc_c=87.38 os/recall_knw=99.47 os/recall_unk=37.65 total/acc_i=70.56 total/acc_c=85.01 total/h_score=52.62
tensor(0)
all:  cs/acc_i=86.90 cs/acc_c=87.38 o

Selected CNT: 3933 / 11775
______
Iteration t=3
all:  cs/acc_i=75.06 cs/acc_c=74.18 os/recall_knw=99.90 os/recall_unk=26.59 total/acc_i=71.92 total/acc_c=73.77 total/h_score=69.63
selected:  cs/acc_i=95.30 cs/acc_c=93.53 os/recall_knw=99.72 os/recall_unk=97.74 total/acc_i=95.96 total/acc_c=93.73 total/h_score=95.59
Selected CNT: 5243 / 11775
______
Iteration t=4
all:  cs/acc_i=81.66 cs/acc_c=81.26 os/recall_knw=99.94 os/recall_unk=26.29 total/acc_i=72.83 total/acc_c=80.01 total/h_score=65.64
selected:  cs/acc_i=94.26 cs/acc_c=93.16 os/recall_knw=99.88 os/recall_unk=84.39 total/acc_i=91.97 total/acc_c=92.75 total/h_score=88.56
Selected CNT: 6550 / 11775
______
Iteration t=5
all:  cs/acc_i=85.70 cs/acc_c=85.99 os/recall_knw=99.97 os/recall_unk=25.65 total/acc_i=72.13 total/acc_c=84.03 total/h_score=58.90
selected:  cs/acc_i=93.40 cs/acc_c=93.16 os/recall_knw=99.96 os/recall_unk=65.23 total/acc_i=86.79 total/acc_c=91.83 total/h_score=76.73
Selected CNT: 7858 / 11775
______
Iteration t=6
a

Selected CNT: 11775 / 11775
______
Iteration t=9
all:  cs/acc_i=86.90 cs/acc_c=87.36 os/recall_knw=99.50 os/recall_unk=44.13 total/acc_i=72.70 total/acc_c=85.30 total/h_score=58.63
selected:  cs/acc_i=86.90 cs/acc_c=87.36 os/recall_knw=99.50 os/recall_unk=44.13 total/acc_i=72.70 total/acc_c=85.30 total/h_score=58.63
tensor(0)
all:  cs/acc_i=86.90 cs/acc_c=87.36 os/recall_knw=99.50 os/recall_unk=44.13 total/acc_i=72.70 total/acc_c=85.30 total/h_score=58.63
sketch -> real lr= 0.001 seed= 0
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=79.52 cs/acc_c=81.12 os/recall_knw=94.62 os/recall_unk=19.30 total/acc_i=58.76 total/acc_c=77.12 total/h_score=31.10
selected:  cs/acc_i=80.34 cs/acc_c=82.07 os/recall_knw=75.46 os/recall_unk=97.29 total/acc_i=81.91 total/acc_c=78.02 total/h_score=86.00
Selected CNT: 2627 / 11775
______
Iteration t=2
all:  cs/acc_i=7

Selected CNT: 6552 / 11775
______
Iteration t=5
all:  cs/acc_i=82.22 cs/acc_c=83.39 os/recall_knw=99.69 os/recall_unk=31.43 total/acc_i=72.76 total/acc_c=81.98 total/h_score=65.33
selected:  cs/acc_i=95.27 cs/acc_c=94.76 os/recall_knw=99.51 os/recall_unk=74.42 total/acc_i=90.02 total/acc_c=93.79 total/h_score=83.37
Selected CNT: 7857 / 11775
______
Iteration t=6
all:  cs/acc_i=83.11 cs/acc_c=84.22 os/recall_knw=99.72 os/recall_unk=37.01 total/acc_i=73.33 total/acc_c=82.77 total/h_score=65.55
selected:  cs/acc_i=93.54 cs/acc_c=93.30 os/recall_knw=99.61 os/recall_unk=67.41 total/acc_i=86.41 total/acc_c=92.06 total/h_score=78.27
Selected CNT: 9168 / 11775
______
Iteration t=7
all:  cs/acc_i=83.72 cs/acc_c=84.76 os/recall_knw=99.71 os/recall_unk=41.87 total/acc_i=73.44 total/acc_c=83.24 total/h_score=65.03
selected:  cs/acc_i=91.36 cs/acc_c=91.39 os/recall_knw=99.64 os/recall_unk=60.64 total/acc_i=82.32 total/acc_c=89.93 total/h_score=72.90
Selected CNT: 10475 / 11775
______
Iteration t=8


tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=80.01 cs/acc_c=81.65 os/recall_knw=85.23 os/recall_unk=45.58 total/acc_i=65.25 total/acc_c=75.45 total/h_score=57.25
selected:  cs/acc_i=68.56 cs/acc_c=73.78 os/recall_knw=52.97 os/recall_unk=99.05 total/acc_i=72.19 total/acc_c=61.00 total/h_score=74.03
Selected CNT: 2634 / 11775
______
Iteration t=2
all:  cs/acc_i=63.46 cs/acc_c=66.15 os/recall_knw=97.71 os/recall_unk=29.92 total/acc_i=72.42 total/acc_c=67.30 total/h_score=76.42
selected:  cs/acc_i=87.35 cs/acc_c=87.05 os/recall_knw=87.62 os/recall_unk=99.07 total/acc_i=92.60 total/acc_c=87.62 total/h_score=92.67
Selected CNT: 3934 / 11775
______
Iteration t=3
all:  cs/acc_i=74.56 cs/acc_c=76.76 os/recall_knw=98.68 os/recall_unk=28.41 total/acc_i=73.07 total/acc_c=76.44 total/h_score=73.27
selected:  cs/acc_i=95.04 cs/acc_c=93.58 os/recall_knw=96.26 os/recall_unk=96.44 total/acc_i=95.45 total/acc_c=93.72 total/h_score=94.99
Selected CNT: 5245 / 11775
______
Iteration t=4
al

Selected CNT: 9165 / 11775
______
Iteration t=7
all:  cs/acc_i=82.97 cs/acc_c=84.15 os/recall_knw=99.22 os/recall_unk=43.87 total/acc_i=73.55 total/acc_c=82.74 total/h_score=66.21
selected:  cs/acc_i=90.51 cs/acc_c=90.57 os/recall_knw=99.05 os/recall_unk=63.04 total/acc_i=82.36 total/acc_c=89.25 total/h_score=74.33
Selected CNT: 10477 / 11775
______
Iteration t=8
all:  cs/acc_i=83.16 cs/acc_c=84.32 os/recall_knw=99.06 os/recall_unk=47.68 total/acc_i=73.04 total/acc_c=82.81 total/h_score=64.84
selected:  cs/acc_i=87.57 cs/acc_c=88.14 os/recall_knw=98.97 os/recall_unk=56.44 total/acc_i=77.76 total/acc_c=86.63 total/h_score=68.81
Selected CNT: 11775 / 11775
______
Iteration t=9
all:  cs/acc_i=83.52 cs/acc_c=84.64 os/recall_knw=98.63 os/recall_unk=52.34 total/acc_i=73.17 total/acc_c=83.10 total/h_score=64.68
selected:  cs/acc_i=83.52 cs/acc_c=84.64 os/recall_knw=98.63 os/recall_unk=52.34 total/acc_i=73.17 total/acc_c=83.10 total/h_score=64.68
tensor(0)
all:  cs/acc_i=83.52 cs/acc_c=84.64 o

Selected CNT: 3932 / 11775
______
Iteration t=3
all:  cs/acc_i=86.79 cs/acc_c=87.89 os/recall_knw=99.92 os/recall_unk=20.07 total/acc_i=76.60 total/acc_c=86.38 total/h_score=68.47
selected:  cs/acc_i=97.82 cs/acc_c=97.50 os/recall_knw=99.81 os/recall_unk=96.55 total/acc_i=97.56 total/acc_c=97.46 total/h_score=97.03
Selected CNT: 5244 / 11775
______
Iteration t=4
all:  cs/acc_i=88.88 cs/acc_c=89.69 os/recall_knw=99.94 os/recall_unk=21.04 total/acc_i=74.63 total/acc_c=87.61 total/h_score=60.76
selected:  cs/acc_i=97.27 cs/acc_c=96.85 os/recall_knw=99.88 os/recall_unk=89.64 total/acc_i=95.94 total/acc_c=96.51 total/h_score=93.11
Selected CNT: 6554 / 11775
______
Iteration t=5
all:  cs/acc_i=89.67 cs/acc_c=90.48 os/recall_knw=99.94 os/recall_unk=23.19 total/acc_i=73.53 total/acc_c=88.12 total/h_score=56.46
selected:  cs/acc_i=96.42 cs/acc_c=96.05 os/recall_knw=99.91 os/recall_unk=72.60 total/acc_i=91.88 total/acc_c=94.94 total/h_score=82.69
Selected CNT: 7857 / 11775
______
Iteration t=6
a

Selected CNT: 11775 / 11775
______
Iteration t=9
all:  cs/acc_i=90.26 cs/acc_c=90.97 os/recall_knw=99.62 os/recall_unk=43.10 total/acc_i=74.62 total/acc_c=88.69 total/h_score=58.49
selected:  cs/acc_i=90.26 cs/acc_c=90.97 os/recall_knw=99.62 os/recall_unk=43.10 total/acc_i=74.62 total/acc_c=88.69 total/h_score=58.49
tensor(0)
all:  cs/acc_i=90.26 cs/acc_c=90.97 os/recall_knw=99.62 os/recall_unk=43.10 total/acc_i=74.62 total/acc_c=88.69 total/h_score=58.49
sketch -> real lr= 0.0001 seed= 1
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=85.92 cs/acc_c=86.79 os/recall_knw=91.54 os/recall_unk=58.28 total/acc_i=74.63 total/acc_c=82.71 total/h_score=68.79
selected:  cs/acc_i=78.18 cs/acc_c=83.22 os/recall_knw=66.28 os/recall_unk=99.65 total/acc_i=83.85 total/acc_c=74.51 total/h_score=84.44
Selected CNT: 2626 / 11775
______
Iteration t=2
all:  cs/acc_i=

Selected CNT: 6551 / 11775
______
Iteration t=5
all:  cs/acc_i=89.71 cs/acc_c=90.56 os/recall_knw=99.91 os/recall_unk=29.61 total/acc_i=77.28 total/acc_c=88.74 total/h_score=66.28
selected:  cs/acc_i=96.76 cs/acc_c=96.53 os/recall_knw=99.86 os/recall_unk=83.12 total/acc_i=93.86 total/acc_c=95.89 total/h_score=89.32
Selected CNT: 7855 / 11775
______
Iteration t=6
all:  cs/acc_i=90.07 cs/acc_c=90.86 os/recall_knw=99.89 os/recall_unk=35.55 total/acc_i=77.61 total/acc_c=89.04 total/h_score=66.55
selected:  cs/acc_i=95.61 cs/acc_c=95.41 os/recall_knw=99.85 os/recall_unk=73.77 total/acc_i=90.38 total/acc_c=94.38 total/h_score=83.20
Selected CNT: 9168 / 11775
______
Iteration t=7
all:  cs/acc_i=90.23 cs/acc_c=90.95 os/recall_knw=99.82 os/recall_unk=41.92 total/acc_i=77.99 total/acc_c=89.16 total/h_score=67.24
selected:  cs/acc_i=94.38 cs/acc_c=94.33 os/recall_knw=99.79 os/recall_unk=65.49 total/acc_i=86.50 total/acc_c=92.95 total/h_score=77.31
Selected CNT: 10475 / 11775
______
Iteration t=8


tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=66.77 cs/acc_c=67.20 os/recall_knw=93.33 os/recall_unk=17.09 total/acc_i=50.10 total/acc_c=63.61 total/h_score=27.14
selected:  cs/acc_i=73.22 cs/acc_c=73.29 os/recall_knw=70.20 os/recall_unk=91.31 total/acc_i=74.40 total/acc_c=69.22 total/h_score=78.03
Selected CNT: 1937 / 8679
______
Iteration t=2
all:  cs/acc_i=54.10 cs/acc_c=54.55 os/recall_knw=94.32 os/recall_unk=20.45 total/acc_i=60.32 total/acc_c=55.46 total/h_score=62.66
selected:  cs/acc_i=72.65 cs/acc_c=73.25 os/recall_knw=74.76 os/recall_unk=93.40 total/acc_i=79.14 total/acc_c=74.21 total/h_score=82.10
Selected CNT: 2899 / 8679
______
Iteration t=3
all:  cs/acc_i=58.08 cs/acc_c=58.16 os/recall_knw=93.54 os/recall_unk=21.75 total/acc_i=57.56 total/acc_c=58.08 total/h_score=57.30
selected:  cs/acc_i=77.50 cs/acc_c=77.29 os/recall_knw=82.49 os/recall_unk=83.96 total/acc_i=79.10 total/acc_c=77.61 total/h_score=80.49
Selected CNT: 3870 / 8679
______
Iteration t=4
all: 

Selected CNT: 6759 / 8679
______
Iteration t=7
all:  cs/acc_i=64.41 cs/acc_c=64.30 os/recall_knw=90.92 os/recall_unk=28.87 total/acc_i=55.61 total/acc_c=62.99 total/h_score=46.82
selected:  cs/acc_i=70.46 cs/acc_c=69.91 os/recall_knw=89.03 os/recall_unk=42.86 total/acc_i=62.85 total/acc_c=68.62 total/h_score=53.14
Selected CNT: 7722 / 8679
______
Iteration t=8
all:  cs/acc_i=65.05 cs/acc_c=64.92 os/recall_knw=90.26 os/recall_unk=30.53 total/acc_i=55.23 total/acc_c=63.46 total/h_score=44.84
selected:  cs/acc_i=67.92 cs/acc_c=67.68 os/recall_knw=89.40 os/recall_unk=36.96 total/acc_i=58.75 total/acc_c=66.22 total/h_score=47.81
Selected CNT: 8679 / 8679
______
Iteration t=9
all:  cs/acc_i=65.12 cs/acc_c=64.97 os/recall_knw=89.05 os/recall_unk=33.67 total/acc_i=55.09 total/acc_c=63.48 total/h_score=44.35
selected:  cs/acc_i=65.12 cs/acc_c=64.97 os/recall_knw=89.05 os/recall_unk=33.67 total/acc_i=55.09 total/acc_c=63.48 total/h_score=44.35
tensor(0)
all:  cs/acc_i=65.12 cs/acc_c=64.97 os/rec

Selected CNT: 3867 / 8679
______
Iteration t=4
all:  cs/acc_i=60.65 cs/acc_c=60.62 os/recall_knw=92.10 os/recall_unk=24.02 total/acc_i=57.46 total/acc_c=60.14 total/h_score=55.19
selected:  cs/acc_i=76.24 cs/acc_c=75.22 os/recall_knw=84.37 os/recall_unk=75.65 total/acc_i=76.11 total/acc_c=75.24 total/h_score=75.44
Selected CNT: 4832 / 8679
______
Iteration t=5
all:  cs/acc_i=62.76 cs/acc_c=62.68 os/recall_knw=91.42 os/recall_unk=26.26 total/acc_i=57.17 total/acc_c=61.85 total/h_score=52.54
selected:  cs/acc_i=75.22 cs/acc_c=74.29 os/recall_knw=86.30 os/recall_unk=64.28 total/acc_i=72.66 total/acc_c=73.82 total/h_score=68.92
Selected CNT: 5793 / 8679
______
Iteration t=6
all:  cs/acc_i=63.32 cs/acc_c=63.22 os/recall_knw=90.59 os/recall_unk=29.77 total/acc_i=57.05 total/acc_c=62.29 total/h_score=51.64
selected:  cs/acc_i=72.76 cs/acc_c=72.12 os/recall_knw=87.05 os/recall_unk=55.01 total/acc_i=68.17 total/acc_c=71.31 total/h_score=62.41
Selected CNT: 6761 / 8679
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=66.54 cs/acc_c=66.94 os/recall_knw=74.88 os/recall_unk=56.07 total/acc_i=58.41 total/acc_c=59.87 total/h_score=58.00
selected:  cs/acc_i=54.35 cs/acc_c=56.94 os/recall_knw=38.53 os/recall_unk=97.37 total/acc_i=61.07 total/acc_c=43.45 total/h_score=57.45
Selected CNT: 1937 / 8679
______
Iteration t=2
all:  cs/acc_i=50.91 cs/acc_c=51.06 os/recall_knw=93.40 os/recall_unk=22.25 total/acc_i=59.96 total/acc_c=52.40 total/h_score=62.12
selected:  cs/acc_i=68.29 cs/acc_c=69.08 os/recall_knw=69.91 os/recall_unk=96.10 total/acc_i=77.49 total/acc_c=70.37 total/h_score=80.38
Selected CNT: 2900 / 8679
______
Iteration t=3
all:  cs/acc_i=56.71 cs/acc_c=56.84 os/recall_knw=92.34 os/recall_unk=22.22 total/acc_i=57.55 total/acc_c=56.96 total/h_score=58.07
selected:  cs/acc_i=75.89 cs/acc_c=75.70 os/recall_knw=79.35 o

Selected CNT: 6760 / 8679
______
Iteration t=7
all:  cs/acc_i=57.89 cs/acc_c=60.51 os/recall_knw=89.02 os/recall_unk=16.91 total/acc_i=46.32 total/acc_c=58.65 total/h_score=31.84
selected:  cs/acc_i=65.15 cs/acc_c=65.18 os/recall_knw=86.73 os/recall_unk=25.05 total/acc_i=54.07 total/acc_c=63.27 total/h_score=36.19
Selected CNT: 7724 / 8679
______
Iteration t=8
all:  cs/acc_i=58.45 cs/acc_c=60.96 os/recall_knw=88.80 os/recall_unk=16.58 total/acc_i=45.71 total/acc_c=58.94 total/h_score=28.38
selected:  cs/acc_i=62.16 cs/acc_c=63.19 os/recall_knw=87.71 os/recall_unk=19.65 total/acc_i=49.30 total/acc_c=61.12 total/h_score=29.98
Selected CNT: 8679 / 8679
______
Iteration t=9
all:  cs/acc_i=58.10 cs/acc_c=60.66 os/recall_knw=88.01 os/recall_unk=16.98 total/acc_i=44.98 total/acc_c=58.58 total/h_score=26.53
selected:  cs/acc_i=58.10 cs/acc_c=60.66 os/recall_knw=88.01 os/recall_unk=16.98 total/acc_i=44.98 total/acc_c=58.58 total/h_score=26.53
tensor(0)
all:  cs/acc_i=58.10 cs/acc_c=60.66 os/rec

Selected CNT: 3868 / 8679
______
Iteration t=4
all:  cs/acc_i=54.20 cs/acc_c=57.13 os/recall_knw=88.68 os/recall_unk=16.29 total/acc_i=49.73 total/acc_c=56.33 total/h_score=47.18
selected:  cs/acc_i=69.67 cs/acc_c=66.79 os/recall_knw=78.91 os/recall_unk=64.80 total/acc_i=68.80 total/acc_c=66.70 total/h_score=65.78
Selected CNT: 4831 / 8679
______
Iteration t=5
all:  cs/acc_i=55.95 cs/acc_c=58.43 os/recall_knw=87.57 os/recall_unk=18.35 total/acc_i=48.97 total/acc_c=57.27 total/h_score=43.04
selected:  cs/acc_i=68.61 cs/acc_c=66.96 os/recall_knw=81.09 os/recall_unk=53.76 total/acc_i=65.70 total/acc_c=66.33 total/h_score=59.64
Selected CNT: 5793 / 8679
______
Iteration t=6
all:  cs/acc_i=57.52 cs/acc_c=60.04 os/recall_knw=87.16 os/recall_unk=19.40 total/acc_i=48.48 total/acc_c=58.57 total/h_score=39.28
selected:  cs/acc_i=67.09 cs/acc_c=66.60 os/recall_knw=82.94 os/recall_unk=39.93 total/acc_i=60.78 total/acc_c=65.33 total/h_score=49.92
Selected CNT: 6759 / 8679
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=56.56 cs/acc_c=59.59 os/recall_knw=72.97 os/recall_unk=51.99 total/acc_i=50.09 total/acc_c=52.47 total/h_score=52.24
selected:  cs/acc_i=51.81 cs/acc_c=59.34 os/recall_knw=36.51 os/recall_unk=96.71 total/acc_i=57.63 total/acc_c=45.94 total/h_score=59.92
Selected CNT: 1938 / 8679
______
Iteration t=2
all:  cs/acc_i=56.15 cs/acc_c=59.04 os/recall_knw=95.47 os/recall_unk=9.28 total/acc_i=51.99 total/acc_c=58.28 total/h_score=49.83
selected:  cs/acc_i=78.52 cs/acc_c=74.48 os/recall_knw=83.31 os/recall_unk=77.41 total/acc_i=78.33 total/acc_c=74.62 total/h_score=75.92
Selected CNT: 2900 / 8679
______
Iteration t=3
all:  cs/acc_i=52.72 cs/acc_c=55.32 os/recall_knw=90.15 os/recall_unk=14.52 total/acc_i=51.15 total/acc_c=54.96 total/h_score=51.28
selected:  cs/acc_i=70.49 cs/acc_c=67.97 os/recall_knw=75.61 os

Selected CNT: 6761 / 8679
______
Iteration t=7
all:  cs/acc_i=55.35 cs/acc_c=55.14 os/recall_knw=89.70 os/recall_unk=33.27 total/acc_i=50.55 total/acc_c=54.43 total/h_score=46.55
selected:  cs/acc_i=61.99 cs/acc_c=61.25 os/recall_knw=87.11 os/recall_unk=45.19 total/acc_i=56.93 total/acc_c=60.49 total/h_score=52.01
Selected CNT: 7724 / 8679
______
Iteration t=8
all:  cs/acc_i=55.85 cs/acc_c=55.66 os/recall_knw=88.53 os/recall_unk=35.77 total/acc_i=50.60 total/acc_c=54.88 total/h_score=46.15
selected:  cs/acc_i=59.05 cs/acc_c=58.60 os/recall_knw=87.26 os/recall_unk=41.23 total/acc_i=53.51 total/acc_c=57.78 total/h_score=48.41
Selected CNT: 8679 / 8679
______
Iteration t=9
all:  cs/acc_i=55.95 cs/acc_c=55.75 os/recall_knw=86.97 os/recall_unk=39.05 total/acc_i=50.56 total/acc_c=54.95 total/h_score=45.93
selected:  cs/acc_i=55.95 cs/acc_c=55.75 os/recall_knw=86.97 os/recall_unk=39.05 total/acc_i=50.56 total/acc_c=54.95 total/h_score=45.93
tensor(0)
all:  cs/acc_i=55.95 cs/acc_c=55.75 os/rec

Selected CNT: 3866 / 8679
______
Iteration t=4
all:  cs/acc_i=51.26 cs/acc_c=51.12 os/recall_knw=90.98 os/recall_unk=27.60 total/acc_i=52.26 total/acc_c=51.27 total/h_score=52.71
selected:  cs/acc_i=68.16 cs/acc_c=66.79 os/recall_knw=80.85 os/recall_unk=70.54 total/acc_i=68.83 total/acc_c=66.97 total/h_score=68.62
Selected CNT: 4832 / 8679
______
Iteration t=5
all:  cs/acc_i=52.24 cs/acc_c=51.95 os/recall_knw=90.26 os/recall_unk=30.42 total/acc_i=51.22 total/acc_c=51.81 total/h_score=50.44
selected:  cs/acc_i=65.61 cs/acc_c=64.36 os/recall_knw=83.18 os/recall_unk=59.84 total/acc_i=63.93 total/acc_c=64.14 total/h_score=62.02
Selected CNT: 5795 / 8679
______
Iteration t=6
all:  cs/acc_i=53.46 cs/acc_c=53.15 os/recall_knw=89.24 os/recall_unk=33.13 total/acc_i=51.08 total/acc_c=52.81 total/h_score=49.31
selected:  cs/acc_i=63.42 cs/acc_c=62.24 os/recall_knw=84.37 os/recall_unk=53.16 total/acc_i=60.36 total/acc_c=61.81 total/h_score=57.34
Selected CNT: 6758 / 8679
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=59.92 cs/acc_c=59.92 os/recall_knw=71.12 os/recall_unk=48.05 total/acc_i=50.41 total/acc_c=51.70 total/h_score=49.89
selected:  cs/acc_i=50.81 cs/acc_c=51.44 os/recall_knw=34.40 os/recall_unk=94.33 total/acc_i=53.71 total/acc_c=36.03 total/h_score=49.03
Selected CNT: 1936 / 8679
______
Iteration t=2
all:  cs/acc_i=37.64 cs/acc_c=38.14 os/recall_knw=90.88 os/recall_unk=24.67 total/acc_i=52.17 total/acc_c=40.29 total/h_score=52.31
selected:  cs/acc_i=53.07 cs/acc_c=52.70 os/recall_knw=55.31 os/recall_unk=93.56 total/acc_i=68.34 total/acc_c=54.64 total/h_score=67.42
Selected CNT: 2899 / 8679
______
Iteration t=3
all:  cs/acc_i=47.91 cs/acc_c=47.82 os/recall_knw=91.27 os/recall_unk=25.83 total/acc_i=52.93 total/acc_c=48.57 total/h_score=54.61
selected:  cs/acc_i=67.45 cs/acc_c=66.01 os/recall_knw=74.59 o

Selected CNT: 6760 / 8679
______
Iteration t=7
all:  cs/acc_i=53.83 cs/acc_c=53.54 os/recall_knw=87.09 os/recall_unk=33.78 total/acc_i=49.89 total/acc_c=52.96 total/h_score=46.74
selected:  cs/acc_i=59.93 cs/acc_c=59.18 os/recall_knw=83.75 os/recall_unk=45.26 total/acc_i=55.44 total/acc_c=58.52 total/h_score=51.29
Selected CNT: 7724 / 8679
______
Iteration t=8
all:  cs/acc_i=54.37 cs/acc_c=54.05 os/recall_knw=85.30 os/recall_unk=36.56 total/acc_i=49.96 total/acc_c=53.41 total/h_score=46.33
selected:  cs/acc_i=57.15 cs/acc_c=56.69 os/recall_knw=83.66 os/recall_unk=42.08 total/acc_i=52.46 total/acc_c=56.00 total/h_score=48.30
Selected CNT: 8679 / 8679
______
Iteration t=9
all:  cs/acc_i=54.36 cs/acc_c=54.06 os/recall_knw=83.71 os/recall_unk=39.63 total/acc_i=49.66 total/acc_c=53.37 total/h_score=45.73
selected:  cs/acc_i=54.36 cs/acc_c=54.06 os/recall_knw=83.71 os/recall_unk=39.63 total/acc_i=49.66 total/acc_c=53.37 total/h_score=45.73
tensor(0)
all:  cs/acc_i=54.36 cs/acc_c=54.06 os/rec

Selected CNT: 3867 / 8679
______
Iteration t=4
all:  cs/acc_i=63.63 cs/acc_c=63.44 os/recall_knw=91.95 os/recall_unk=20.45 total/acc_i=57.94 total/acc_c=62.60 total/h_score=53.20
selected:  cs/acc_i=77.75 cs/acc_c=76.64 os/recall_knw=84.76 os/recall_unk=76.08 total/acc_i=77.42 total/acc_c=76.62 total/h_score=76.36
Selected CNT: 4830 / 8679
______
Iteration t=5
all:  cs/acc_i=64.47 cs/acc_c=64.31 os/recall_knw=90.90 os/recall_unk=22.25 total/acc_i=56.76 total/acc_c=63.16 total/h_score=49.53
selected:  cs/acc_i=76.12 cs/acc_c=75.16 os/recall_knw=86.02 os/recall_unk=62.73 total/acc_i=73.40 total/acc_c=74.57 total/h_score=68.39
Selected CNT: 5791 / 8679
______
Iteration t=6
all:  cs/acc_i=65.66 cs/acc_c=65.56 os/recall_knw=90.15 os/recall_unk=24.35 total/acc_i=56.44 total/acc_c=64.18 total/h_score=47.09
selected:  cs/acc_i=74.14 cs/acc_c=73.53 os/recall_knw=86.95 os/recall_unk=50.60 total/acc_i=68.73 total/acc_c=72.44 total/h_score=59.95
Selected CNT: 6759 / 8679
______
Iteration t=7
all: 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
tensor(True) tensor(True)
______
Iteration t=1
all:  cs/acc_i=67.55 cs/acc_c=68.21 os/recall_knw=83.01 os/recall_unk=42.09 total/acc_i=56.54 total/acc_c=63.03 total/h_score=50.81
selected:  cs/acc_i=59.39 cs/acc_c=62.57 os/recall_knw=47.93 os/recall_unk=95.88 total/acc_i=65.51 total/acc_c=53.16 total/h_score=66.61
Selected CNT: 1936 / 8679
______
Iteration t=2
all:  cs/acc_i=53.59 cs/acc_c=54.21 os/recall_knw=93.45 os/recall_unk=21.13 total/acc_i=61.47 total/acc_c=55.36 total/h_score=64.06
selected:  cs/acc_i=69.64 cs/acc_c=71.02 os/recall_knw=70.77 os/recall_unk=95.59 total/acc_i=77.84 total/acc_c=72.19 total/h_score=81.49
Selected CNT: 2899 / 8679
______
Iteration t=3
all:  cs/acc_i=58.37 cs/acc_c=58.60 os/recall_knw=92.01 os/recall_unk=20.16 total/acc_i=57.75 total/acc_c=58.49 total/h_score=57.49
selected:  cs/acc_i=76.18 cs/acc_c=75.89 os/recall_knw=79.22 o

Selected CNT: 6758 / 8679
______
Iteration t=7
all:  cs/acc_i=65.86 cs/acc_c=65.99 os/recall_knw=88.56 os/recall_unk=28.32 total/acc_i=56.58 total/acc_c=64.60 total/h_score=47.23
selected:  cs/acc_i=71.70 cs/acc_c=71.58 os/recall_knw=86.40 os/recall_unk=43.87 total/acc_i=64.34 total/acc_c=70.27 total/h_score=54.40
Selected CNT: 7725 / 8679
______
Iteration t=8
all:  cs/acc_i=66.74 cs/acc_c=66.96 os/recall_knw=88.02 os/recall_unk=30.09 total/acc_i=56.29 total/acc_c=65.39 total/h_score=45.06
selected:  cs/acc_i=69.80 cs/acc_c=69.69 os/recall_knw=87.03 os/recall_unk=36.73 total/acc_i=60.09 total/acc_c=68.12 total/h_score=48.10
Selected CNT: 8679 / 8679
______
Iteration t=9
all:  cs/acc_i=67.11 cs/acc_c=67.38 os/recall_knw=87.28 os/recall_unk=32.30 total/acc_i=56.01 total/acc_c=65.71 total/h_score=43.67
selected:  cs/acc_i=67.11 cs/acc_c=67.38 os/recall_knw=87.28 os/recall_unk=32.30 total/acc_i=56.01 total/acc_c=65.71 total/h_score=43.67
tensor(0)
all:  cs/acc_i=67.11 cs/acc_c=67.38 os/rec

In [13]:
results.to_csv('results/dcc__conf__small__NN_N+1__nn_raw.csv', header=True, index=False)

In [20]:
# df = pd.read_csv('office_home_oslpp_nn_raw.csv')
# df['h_score'] = df['desc'].apply(lambda x: float(x.split()[-1].split('=')[-1]))
# import matplotlib.pyplot as plt
# for n, gr in df.groupby(['source', 'target']):
#     stat = gr.groupby(['lr', 'n_r'])['h_score'].mean()
#     exps = np.array(list(stat.index))
#     fig, ax = plt.subplots()
#     ax.scatter(exps[:, 0], exps[:, 1], c=stat.values)
#     for i, txt in enumerate(stat.values):
#         ax.annotate(round(txt, 2), (exps[i][0], exps[i][1]))
#     plt.title(n)
#     plt.xlabel('lr')
#     plt.ylabel('n_r')
#     plt.xticks(exps[:, 0])
#     plt.yticks(exps[:, 1])
#     fig.colorbar(ax.get_children()[0])
#     plt.show()

In [15]:
results

source    target                                               desc  \
0    painting    sketch  cs/acc_i=48.70 cs/acc_c=50.07 os/recall_knw=87...   
1    painting    sketch  cs/acc_i=48.53 cs/acc_c=49.85 os/recall_knw=88...   
2    painting    sketch  cs/acc_i=48.85 cs/acc_c=50.27 os/recall_knw=87...   
3    painting    sketch  cs/acc_i=48.82 cs/acc_c=50.38 os/recall_knw=87...   
4    painting    sketch  cs/acc_i=48.18 cs/acc_c=49.44 os/recall_knw=86...   
..        ...       ...                                                ...   
211    sketch  painting  cs/acc_i=66.62 cs/acc_c=66.92 os/recall_knw=87...   
212    sketch  painting  cs/acc_i=65.93 cs/acc_c=66.13 os/recall_knw=86...   
213    sketch  painting  cs/acc_i=66.50 cs/acc_c=66.73 os/recall_knw=86...   
214    sketch  painting  cs/acc_i=67.11 cs/acc_c=67.38 os/recall_knw=87...   
215    sketch  painting  cs/acc_i=66.05 cs/acc_c=66.29 os/recall_knw=86...   

         lr  seed  epochs   n_r  
0    0.0010   0.0    10.0  0.10  
1    0.0010   1.0    10.0  0.10  
2    0.0010   2.0    10.0  0.10  
3    0.0010   0.0    10.0  0.25  
4    0.0010   1.0    10.0  0.25  
..      ...   ...     ...   ...  
211  0.0001   1.0    50.0  0.25  
212  0.0001   2.0    50.0  0.25  
213  0.0001   0.0    50.0  0.35  
214  0.0001   1.0    50.0  0.35  
215  0.0001   2.0    50.0  0.35  

[216 rows x 7 columns]

In [30]:
results['epoch'] = pd.Series(results.index).apply(lambda i: epochs[(i // 9) % 3])

In [16]:
wd = results.copy()
wd['h_score'] = wd['desc'].apply(lambda x: float(x.split()[-1].split('=')[-1]))

In [17]:
wd

source    target                                               desc  \
0    painting    sketch  cs/acc_i=48.70 cs/acc_c=50.07 os/recall_knw=87...   
1    painting    sketch  cs/acc_i=48.53 cs/acc_c=49.85 os/recall_knw=88...   
2    painting    sketch  cs/acc_i=48.85 cs/acc_c=50.27 os/recall_knw=87...   
3    painting    sketch  cs/acc_i=48.82 cs/acc_c=50.38 os/recall_knw=87...   
4    painting    sketch  cs/acc_i=48.18 cs/acc_c=49.44 os/recall_knw=86...   
..        ...       ...                                                ...   
211    sketch  painting  cs/acc_i=66.62 cs/acc_c=66.92 os/recall_knw=87...   
212    sketch  painting  cs/acc_i=65.93 cs/acc_c=66.13 os/recall_knw=86...   
213    sketch  painting  cs/acc_i=66.50 cs/acc_c=66.73 os/recall_knw=86...   
214    sketch  painting  cs/acc_i=67.11 cs/acc_c=67.38 os/recall_knw=87...   
215    sketch  painting  cs/acc_i=66.05 cs/acc_c=66.29 os/recall_knw=86...   

         lr  seed  epochs   n_r  h_score  
0    0.0010   0.0    10.0  0.10    44.19  
1    0.0010   1.0    10.0  0.10    42.12  
2    0.0010   2.0    10.0  0.10    44.70  
3    0.0010   0.0    10.0  0.25    42.28  
4    0.0010   1.0    10.0  0.25    44.69  
..      ...   ...     ...   ...      ...  
211  0.0001   1.0    50.0  0.25    42.87  
212  0.0001   2.0    50.0  0.25    42.61  
213  0.0001   0.0    50.0  0.35    45.17  
214  0.0001   1.0    50.0  0.35    43.67  
215  0.0001   2.0    50.0  0.35    43.95  

[216 rows x 8 columns]

In [18]:
wd.groupby(['source', 'target', 'lr', 'n_r', 'epochs'])['h_score'].mean().to_frame(name = 'h_score').reset_index().sort_values(by='h_score', ascending=False).drop_duplicates(['source', 'target'])

source    target     lr   n_r  epochs    h_score
70    sketch      real  0.001  0.35    10.0  69.830000
11  painting      real  0.001  0.35    50.0  68.933333
35      real  painting  0.001  0.35    50.0  59.510000
43      real    sketch  0.001  0.10    50.0  48.450000
58    sketch  painting  0.001  0.35    10.0  46.916667
23  painting    sketch  0.001  0.35    50.0  46.120000

In [19]:
wd.pivot(index=['lr', 'epochs', 'n_r'], columns=['source', 'target'], values='h_score')

ValueError: Index contains duplicate entries, cannot reshape

In [ ]:
wd.set_index(['lr', 'epoch', 'n_r']).head(30)

In [44]:
wd = pd.read_csv('results/dcc__entropy__StepLR__50_epochs__nn_raw.csv')

In [45]:
wd['h_score'] = wd['desc'].apply(lambda x: float(x.split()[-1].split('=')[-1]))

In [46]:
wd

source          target  \
0  painting_train      real_train   
1  painting_train    sketch_train   
2      real_train  painting_train   
3      real_train    sketch_train   
4    sketch_train  painting_train   
5    sketch_train      real_train   

                                                desc      lr  seed   n_r  \
0  cs/acc_i=59.98 cs/acc_c=60.09 os/recall_knw=71...  0.0005   0.0  0.15   
1  cs/acc_i=26.40 cs/acc_c=25.41 os/recall_knw=53...  0.0005   0.0  0.15   
2  cs/acc_i=39.74 cs/acc_c=39.39 os/recall_knw=65...  0.0005   0.0  0.15   
3  cs/acc_i=24.48 cs/acc_c=23.68 os/recall_knw=51...  0.0005   0.0  0.15   
4  cs/acc_i=37.51 cs/acc_c=34.45 os/recall_knw=70...  0.0005   0.0  0.15   
5  cs/acc_i=56.05 cs/acc_c=57.00 os/recall_knw=71...  0.0005   0.0  0.15   

   h_score  
0    54.40  
1    30.42  
2    40.83  
3    29.29  
4    35.06  
5    48.56